### ISSUE TITLE
Improve discoverability of features

### ISSUE THREAD

**Issue by varkor** [varkor/quiver#10]
This is intentionally vague, as there are several ways in which this could be achieved and I'll have to investigate to work out how best to tackle this. E.g. an interface rehaul, a tutorial, or so on.

**Comment by vikraman** [comment]
This is quite important, for example, I couldn't figure out how to draw pullbacks.

**Comment by varkor** [comment]
I've done some work on improving usability, with a panel explaining keyboard shortcuts, and also making the button for pullbacks more explicit in https://github.com/varkor/quiver/pull/39.
