### ISSUE TITLE
tikzcd returns an error on a simple diagram

### ISSUE THREAD

**Issue by suhr** [varkor/quiver#100]
For https://q.uiver.app/?q=WzAsMyxbMCwxLCJBIl0sWzIsMSwiQiJdLFsyLDAsIkIiXSxbMCwxLCJmIiwyXSxbMCwyLCJmIl0sWzIsMSwiXFxtYXRocm17aWR9X0IiXV0=, Quiver generates the following code:

```
% https://q.uiver.app/?q=WzAsMyxbMCwxLCJBIl0sWzIsMSwiQiJdLFsyLDAsIkIiXSxbMCwxLCJmIiwyXSxbMCwyLCJmIl0sWzIsMSwiXFxtYXRocm17aWR9X0IiXV0=
\[\begin{tikzcd}
	&& B \\
	A && B
	\arrow["f"', from=2-1, to=2-3]
	\arrow["f", from=2-1, to=1-3]
	\arrow["{\mathrm{id}_B}", from=1-3, to=2-3]
\end{tikzcd}\]
```

But trying to use it with XeLaTeX gives the following error:

```
! Package pgfkeys Error: I do not know the key '/tikz/"f"'' and I am going to i
gnore it. Perhaps you misspelled it.

See the pgfkeys package documentation for explanation.
Type  H <return>  for immediate help
...
l.113 I think the culprit is a tikzcd arrow in cell 2-3.
\errmessage ...currentrow -\tikzcd@currentcolumn }
                                                  
l.116 \end{tikzcd}
                  \]
```

**Comment by varkor** [comment]
Are you including `quiver.sty`? This example doesn't result in any error for me.

**Comment by suhr** [comment]
Yes, I do. This is the file: https://gist.github.com/suhr/843e1a02155fb089b7520e100cedd610

TeXlive is installed with `texlive.combine { inherit (texlive) scheme-medium collection-langcyrillic marginnote eulervm tikz-cd; }` in NixOS. Maybe I need an another obscure TeX package to make it work?

**Comment by suhr** [comment]
Additional info: removing labels makes it compile. But unfortunately, labels matter.

**Comment by varkor** [comment]
Does the following example compile for you?
```latex
\documentclass{article}

\usepackage{quiver}

\begin{document}

% https://q.uiver.app/?q=WzAsMyxbMCwxLCJBIl0sWzIsMSwiQiJdLFsyLDAsIkIiXSxbMCwxLCJmIiwyXSxbMCwyLCJmIl0sWzIsMSwiXFxtYXRocm17aWR9X0IiXV0=
\[\begin{tikzcd}
	&& B \\
	A && B
	\arrow["f"', from=2-1, to=2-3]
	\arrow["f", from=2-1, to=1-3]
	\arrow["{\mathrm{id}_B}", from=1-3, to=2-3]
\end{tikzcd}\]

\end{document}
```
This is a minimal example that compiles for me.

**Comment by suhr** [comment]
It finds out, importing `quotes` after `quiver` fixed the issue.

**Comment by varkor** [comment]
Great, I'm glad you found a solution! This is a useful fact to know (LaTeX can be such a pain with package ordering problems).

**Comment by suhr** [comment]
It is not really about package order, but the fact I needed to import `quotes` at all. It might make sense to add `\RequirePackage{quotes}` to `quiver.sty` if it does not break anything.

**Comment by varkor** [comment]
Oh, I misunderstood. But `quotes` is a package that converts double quotes to LaTeX quotation marks. That shouldn't be necessary here, because the `"` characters in TikZ are not supposed to be LaTeX quotation marks. So I'm not sure what's going on. I feel it's quite likely another package you're using is conflicting with TikZ.
