### ISSUE TITLE
Is it possible to run Quiver locally using static html files + javascript

### ISSUE THREAD

**Issue by enjoysmath** [varkor/quiver#105]
I was wanting to load the Quiver editor from an html file viewed using a QWebEngineView (Qt Framework) browser, but also have the editor work when offline.  Is this possible?

If not, what changes would I have to make such as say reading the URL parameters from a file since there is no HTTP server in this setup.

**Comment by varkor** [comment]
Yes, you should just be able to follow the [build instruction](https://github.com/varkor/quiver#building) and then open `index.html` locally.
