### ISSUE TITLE
Drawing quivers obtained via QPA directly with the quiver program

### ISSUE THREAD

**Issue by Nakayamaalgebra** [varkor/quiver#113]
Thank you very much for this nice tool.
I am using QPA (https://folk.ntnu.no/oyvinso/QPA/), a GAP-package for quiver algebras.
One can obtain many quivers using QPA, for example as subalgebras, endomorphism rings....
My question is whether there is an easy way to directly draw a quiver obtained from QPA using your tool.
Here is an example from QPA:
Quiver( ["v1_op","v2_op","v3_op","v4_op","v5_op","v6_op","v7_op","v8_op","v9_op","v10_op"], [["v2_op","v1_op","a1_op"],["v3_op","v2_op","a2_op"],["v4_op","v2_op","a3_op"],["v5_op","v3_op","a4_op"],["v5_op","v4_op","a5_op"],["v7_op","v4_op","a6_op"],["v6_op"\
,"v5_op","a7_op"],["v8_op","v5_op","a8_op"],["v9_op","v6_op","a9_op"],["v8_op","v7_op","a10_op"],["v9_op","v8_op","a11_op"],["v10_op","v9_op","a12_op"]] )

The first list ["v1_op","v2_op","v3_op","v4_op","v5_op","v6_op","v7_op","v8_op","v9_op","v10_op"] are the names of the vertices, for example v2_op. The second list [["v2_op","v1_op","a1_op"],["v3_op","v2_op","a2_op"],["v4_op","v2_op","a3_op"],["v5_op","v3_op","a4_op"],["v5_op","v4_op","a5_op"],["v7_op","v4_op","a6_op"],["v6_op"\
,"v5_op","a7_op"],["v8_op","v5_op","a8_op"],["v9_op","v6_op","a9_op"],["v8_op","v7_op","a10_op"],["v9_op","v8_op","a11_op"],["v10_op","v9_op","a12_op"]]  are the names of the arrows where for example ["v3_op","v2_op","a2_op"] means that there is an arrow from v3_op to v2_op with name a2_op. 
(names of vertices and arrows in QPA can be a bit weird,depending how the quiver was constructed (here a opposite quiver appeared))

Thank you for any help or comments.

**Comment by enjoysmath** [comment]
@Nakayamaalgebra  there isn't as far as I know.  If you need help editing the source code, I have personally decoded into a Python class the base64-encoded JSON format (what Quiver Editor outputs) which looks similar to your format only in the part about vertices essentially, and maybe not even those (I forgot what the format is precisely).  You'll have to check comments in the Quiver source code for specifics about the format.  There's a lot of other attached attributes that you can forget and include, respectively for the QPA <- JSON  and JSON <- QPA functions.

So you need to do (Quiver -> JSON -> base64) -> JSON -> Your format deleting the color & style info -> QPA so you only need to code one of those arrows (JSON -> Your format) but also the reverse direction.  You then load the base64 into q.uiver.app naturally by passing it in the URL, the same as what appears when you click "Shareable Link" in Quiver.  You use a library to go from base64 -> JSON dictionary in whatever language you're doing this in.  That is a common transformation, so there should exist a library for JS (for client side) or whatever server side language you're working with.

In fact if you go base64 -> JSON on client side, you might as well do everything in JS, and copy what Quiver does to go from base64->JSON and back.

**Comment by varkor** [comment]
@Nakayamaalgebra: sorry for the delay. At the moment, there isn't a completely straightforward way to do this, but if you're willing to do a little scripting, you should be able to write something that outputs the base 64 that **quiver** takes as input, as @enjoysmath suggests. The place to look in the code is here:
https://github.com/varkor/quiver/blob/cfe491824a78382babb015dde86696eaa51b6c60/src/quiver.js#L693-L735
This is the code that **quiver** uses to export a diagram. If you produce JSON similar to this (you can ignore most of the complexities, like arrow style, etc.), you should be able to load it into **quiver** without much trouble. I'm happy to answer more specific questions about this.

**Comment by varkor** [comment]
I'm going to close this issue, but let me know if you have any more questions.
