### ISSUE TITLE
Any chance of better mobile support (iPhone 6/7/8/X)?

### ISSUE THREAD

**Issue by enjoysmath** [varkor/quiver#117]
Here is a screenshot of this Django site I'm working on that has some slight modifications to current version of varkor/quiver.

![image](https://user-images.githubusercontent.com/1606391/135439786-11c9448d-6e6e-4519-b373-e530b9ab27b2.png)

** To Replicate:**

   Open https://q.uiver.app.  Hit F12 to open dev tools in Chrome and second from the top left of the dev tools there's a devices button.  Click that, in the drop down menu at the top of the screen make sure iPhone6/7/8 is selected.  I think I  have an old iPhone, so I'm assuming it's 6.

Anyway, place an arrow and select the arrow.  The arrow styling panel pops open and covers the whole screen:

![image](https://user-images.githubusercontent.com/1606391/135440229-fa271454-5a4a-4992-9de3-fcaf7303bca7.png)

I think on mobile, the background of these should go to a translucent colored background.  That's what I'm doing for a pop-up search box but outside of Quiver's app, using a Django template/Bootstrap5.

**Comment by enjoysmath** [comment]
This is the best result I've got just making things transparent:

![image](https://user-images.githubusercontent.com/1606391/135659182-5f150c68-9ce8-4079-8f50-30564cbaa6ae.png)

So my thinking now is that I'm going to move all the buttons of quiver into a Bootstrap5 template and communicate their settings over to Quiver using Javascript calls.   Will take a while, but perhaps it will be worth it for mobile support.

**Edit**:
The buttons can be overridden without Javascript calls in or out - you just give your buttons id's such as "save-button" etc.

**Comment by varkor** [comment]
Mobile editing isn't very high priority for me, because most people edit on computers, but I will leave the issue open for if I ever do have time.

**Comment by enjoysmath** [comment]
I'm moving your buttons into a Bootstrap template.  There's not much code
changes required to do that other than the addition of an external html
template (mine's a Django template).

Let me know if you would like this done for your code.  Bootstrap is easy /
nice to use and takes care of any mobile issues as the page auto collapses
if you code it per the recipes.

**Comment by enjoysmath** [comment]
I'm doing this for every button in Quiver, including the arrow edit panel
(which includes a lot of stuff) and using dropdowns, tabs, & collapses
where possible in order to allow the user to edit an arrow property while
viewing the arrow, because right now it covers the whole screen.  Other
than that, the drawing works superbly well on mobile - have you tried it on
your phone?

**Comment by varkor** [comment]
> have you tried it on your phone?

I spent quite a long time making sure that touch support worked well. However, I didn't spend so much time making sure the interface more generally worked well on a small screen, because I had imagined that most touchscreen users would be editing on tablets rather than phones.

**Comment by Iey4iej3** [comment]
The performance on small screens is not good. A key problem is that the toolbar and the bottom are not scrollable, and it is difficult to select the URL of the shared link.

**Comment by enjoysmath** [comment]
@Iey4iej3 Here are some of the results I'm getting using BSS (Bootstrap Studio) to create a responsive quiver integration into my database site:

![image](https://github.com/varkor/quiver/assets/1606391/aaea5acc-e9c2-4ad5-ba0a-267f181755b7)

MathDOPE = Database of Proof Explanations

So as you can see I broke up the huge arrow settings popup that definitely doesn't work on any mobile smaller than tablet; into menu pop-up modals which is why the background is greyed out - a modal popped up and that's the default effect in BSS.
