### ISSUE TITLE
Bug with my mod of Quiver (both overly HTML elements AND quiver editor receive mouse clicks)

### ISSUE THREAD

**Issue by enjoysmath** [varkor/quiver#119]
Well, actually two bugs I'm looking at now.  When I click stuff in my external-to-quiver HTML toolbar, the  mouse clicks also go to the quiver editor in the background (the button panel overlays Quiver).

Secondly, when I click on any of the buttons, all the content in the canvas appears to get deleted.  So you can't even zoom in without wiping out the diagram, although zooming in does work (you can tell by its effect on the grid).

So I thought the first bug may be causing the second bug, so I would like to focus on the first one.  How would I stop propagation of the event to the canvas?  As you can see on the right, my naive `event.stopPropagation()` does  nothing to fix this.

Doing the below on line 5482 of `ui.js` has no effect on this:

```
            const trigger_action_and_update_toolbar = (event) => {
                action.call(button, event);
                ui.toolbar.update(ui);
                event.stopPropagation();
                return true;
            };

```

I also tried `event.stopImmediatePropagation()` and `return false` there.
Here is [the video showing both bugs](https://youtu.be/ABs6HYqDr2s).

**Comment by enjoysmath** [comment]
Okay, using your privided "dom.js/cancel(event)" method seems to repair the zoom in / out and items to center buttons, but there is still vertex placement going on behind the buttons.  And the other buttons are still broken.  So I will hack on it some more and post back here when I have it debugged.

```
            const trigger_action_and_update_toolbar = (event) => {
                action.call(button, event);
                ui.toolbar.update(ui);
                cancel(event);
                return false;
            };
```

Okay, so all the buttons work except for the Delete button.  However, when you click on a button, the canvas still receives a place vertext / edge click.  So how can I prevent this event from happening?

**Comment by enjoysmath** [comment]
Fixed it with a hack flag check at line 1173 of ui.js:

```
        this.element.listen(pointer_event("down"), (event) => {
            if (event.button === 0) {
                if (! this.toolbar.cancelled_event) {

```

Where initialize it to false in Toolbar's constructor and set it to true when I need to cancel(event) after clicking a button.  It works for the most part, except the first click on the toolbar repositions the focus "grey square" / "Add vertex", but only once.  This is useable enough.

Edit, my mistake for closing this issue, but the above code does not fix the issue I'm having.

**Comment by varkor** [comment]
Unfortunately, I don't have time to debug an issue that's not directly relevant to **quiver**. However, I would make sure that your event handlers for the buttons are being added before **quiver**'s event handlers so that yours take priority, and then `cancel` the click/pointer events once you've received them. I often find getting the precedence correct can be a bit of a pain, and sometimes it just requires trying various combinations until you figure out how to get it to work.
