### ISSUE TITLE
Shorter URLs

### ISSUE THREAD

**Issue by jliptrap** [varkor/quiver#121]
Long URLs are inconvenient to embed in code comments, e.g., they're not clickable from horizontal splits in Neovim.  This is much less of an issue in LaTeX than in, e.g., Haskell or Agda.  Since quiver URLs aren't human-readable anyway, why not shorten them so that users avoid the manual labor of going through a 3rd party URL shortener?

**Comment by varkor** [comment]
**quiver** is serverless, which significantly decreases code and infrastructure complexity. However, it means that the data for the entire diagram must be stored in the URL. Short of using a third-party URL-shortening service, I don't think there's much possiblity for shortening further; the encoding scheme already tries to be clever. Regarding relying on third-party shorteners: this seems like a recipe for URLs that break in the future, which it is very important is avoided.

**Comment by jliptrap** [comment]
That makes sense, long URLs sound like the way to go then, in which case managing them seems like a job for editor tooling rather than quiver itself.  Thanks!
