### ISSUE TITLE
Adding equality as one of possible arrow line styles

### ISSUE THREAD

**Issue by eliasguisado** [varkor/quiver#123]
That's it. It would be nice that apart from all the current available arrow line styles:
![image](https://user-images.githubusercontent.com/26608543/139574399-bc717e54-aa2a-417e-b2b1-092fb4872b3b.png)
also equality would be available, like it is done on this diagram for A and B:
![image](https://user-images.githubusercontent.com/26608543/139574413-16637c47-4f52-4b50-b726-9b4039df9bdc.png)

**Comment by varkor** [comment]
I admit that it's not very discoverable at the moment, but it's possible to have equality in a diagram at the moment: you can change the Level of an arrow to 2, and then remove the arrowhead: [example diagram](https://q.uiver.app/?q=WzAsNCxbMCwwLCJBIl0sWzAsMSwiQSJdLFsxLDAsIkIiXSxbMSwxLCJCIl0sWzAsMiwiZiJdLFsxLDMsImYiLDJdLFswLDEsIiIsMix7ImxldmVsIjoyLCJzdHlsZSI6eyJoZWFkIjp7Im5hbWUiOiJub25lIn19fV0sWzIsMywiIiwwLHsibGV2ZWwiOjIsInN0eWxlIjp7ImhlYWQiOnsibmFtZSI6Im5vbmUifX19XV0=).

**Comment by varkor** [comment]
I'm going to close this for now, but I would welcome suggestions on making this more discoverable.
