### ISSUE TITLE
Several labels on a single arrow

### ISSUE THREAD

**Issue by eliasguisado** [varkor/quiver#124]
At times it's convenient to add two labels on a same arrow, as for example to point out that some arrow is an isomorphism at the same time we write its name:
![image](https://user-images.githubusercontent.com/26608543/139574485-c0d6acf3-0899-4c2b-a3b6-fa21b5835d2e.png)
In this diagram, in the arrow B→A⊕C from the middle, on the left side there is \cong and on the right side \phi, but currently on q.uiver.app only one label per arrow is allowed.

**Comment by varkor** [comment]
Closing in favour of https://github.com/varkor/quiver/issues/92. I agree this is a desirable feature. In some cases (such as in your diagram) you can achieve the same effect by drawing two arrows on top of each other, but this is a workaround, and I'd like to support it properly.
