### ISSUE TITLE
Generated tikzcd inconsistency

### ISSUE THREAD

**Issue by ice1000** [varkor/quiver#125]
https://q.uiver.app/?q=WzAsOCxbMCwyXSxbNiwyLCJ4Il0sWzMsNF0sWzMsMCwieSJdLFsxLDJdLFszLDIsIlxcYnVsbGV0Il0sWzIsMl0sWzUsMl0sWzAsMV0sWzIsM10sWzUsMiwiLTEiLDAseyJzdHlsZSI6eyJoZWFkIjp7Im5hbWUiOiJub25lIn19fV0sWzUsNywiMSIsMCx7InN0eWxlIjp7ImhlYWQiOnsibmFtZSI6Im5vbmUifX19XSxbMyw1LCIxIiwwLHsibGFiZWxfcG9zaXRpb24iOjQwLCJzdHlsZSI6eyJoZWFkIjp7Im5hbWUiOiJub25lIn19fV0sWzUsOCwiIiwwLHsic2hvcnRlbiI6eyJ0YXJnZXQiOjIwfX1dLFsxMCwxMSwiIiwwLHsibGV2ZWwiOjEsInN0eWxlIjp7ImhlYWQiOnsibmFtZSI6Im5vbmUifX19XSxbMTIsMTEsIiIsMix7ImxldmVsIjoxLCJzdHlsZSI6eyJoZWFkIjp7Im5hbWUiOiJub25lIn19fV0sWzQsOCwiLTEiLDAseyJsYWJlbF9wb3NpdGlvbiI6NDAsImxldmVsIjoxLCJzdHlsZSI6eyJib2R5Ijp7Im5hbWUiOiJub25lIn0sImhlYWQiOnsibmFtZSI6Im5vbmUifX19XSxbMTYsMTAsIiIsMCx7ImxldmVsIjoxLCJzdHlsZSI6eyJoZWFkIjp7Im5hbWUiOiJub25lIn19fV0sWzE2LDEyLCIiLDIseyJsZXZlbCI6MSwic3R5bGUiOnsiaGVhZCI6eyJuYW1lIjoibm9uZSJ9fX1dXQ==

Web
![image](https://user-images.githubusercontent.com/16398479/139730851-594168c7-187d-42c1-85bd-239b7b6bd649.png)

LaTeX (Latexmk, John Collins, 29 September 2020. Version 4.70b with `latexmk -pdf` and quiver package included)
![image](https://user-images.githubusercontent.com/16398479/139730880-1c2b54e6-197a-4b6d-92d0-25dfca581718.png)

**Comment by ice1000** [comment]
Look at the arrow

**Comment by varkor** [comment]
Is that link correct? **quiver** says the diagram is malformed, which either means you pasted an incorrect link, or that **quiver** is generating an incorrect link. If it's the latter, it'll help if you could figure out a way to create a diagram that causes this issue.

**Comment by ice1000** [comment]
> Is that link correct? **quiver** says the diagram is malformed, which either means you pasted an incorrect link, or that **quiver** is generating an incorrect link. If it's the latter, it'll help if you could figure out a way to create a diagram that causes this issue.

After some debugging I realized it's my fault (I didn't draw the right thing in quiver, and the tikzcd output is expected), and I cannot find the working link now. Maybe I modified the link accidentally.

Sorry 🙏
