### ISSUE TITLE
code | export direct to Obsidian

### ISSUE THREAD

**Issue by ephiljones** [varkor/quiver#126]

**Comment by varkor** [comment]
Could you please expand? What is Obsidian?

**Comment by ephiljones** [comment]
quick question: 
how do i make a copy of a q.uiver tab (and thus of a diagram)?

i stumbled on to doing it once, but can’t figure out how i did it:)


Emerson Philip Jones
MGP 202898

**Comment by ephiljones** [comment]
ahh. 
use shareable link:)

varkor, this is a fantastic product.
thank you so much!


Emerson Philip Jones
MGP 202898

Begin forwarded message:

> From: Philip Jones ***@***.***>
> Date: December 23, 2021 at 10:04:21 PM EST
> To: varkor/quiver ***@***.***>
> Subject: Re: [varkor/quiver] code | export direct to Obsidian (Issue #126)
> 
> ﻿quick question: 
> how do i make a copy of a q.uiver tab (and thus of a diagram)?
> 
> i stumbled on to doing it once, but can’t figure out how i did it:)
> 
> 
> Emerson Philip Jones
> MGP 202898
>

**Comment by varkor** [comment]
> how do i make a copy of a q.uiver tab (and thus of a diagram)?

Yes, you can either get the shareable link, or save the diagram (which updates the URL) and copy the URL, which contains the data for the entire diagram.

I will close this issue, as it seems you have answered your question, but let me know if there was anything else you intended this issue for.

**Comment by ephiljones** [comment]
Emerson Philip Jones
MGP 202898
