### ISSUE TITLE
Dynamically updated diagram urls

### ISSUE THREAD

**Issue by vikraman** [varkor/quiver#13]
I have a minor issue that happens when I leave a quiver tab open with an incomplete diagram, and then the tab gets snoozed by my browser, so when I return to it, the tab refreshes and I lose my work. 

I wonder if the diagram could be encoded as a uri hash fragment in the url (rather than a query string as it is currently done), that updates dynamically while drawing the diagram. This would make it possible to use the browser history/forward/back buttons to interact with the diagram history.

**Comment by varkor** [comment]
I've considered something like this. Would you expect the Back/Forward buttons in the browser to act like Undo/Redo in the editor? I think it may make more sense to record the current diagram in the URL, but replace the current browser history entry, so that quiver doesn't generate new history entries for every small change to the diagram.

**Comment by vikraman** [comment]
I think it would be convenient to have my browser back/forward keyboard shortcuts also do undo/redo, but I could also just learn the quiver undo/redo shortcuts.

**Comment by varkor** [comment]
The undo/redo shortcuts should be the same as most other programs: Command/Control-Z for undo and Command/Control-Shift-Z for redo.

**Comment by varkor** [comment]
With https://github.com/varkor/quiver/commit/b4f637585ecf28cbc5065f0bb2d831616cb703db, you can now save the current diagram to the URL, and, with https://github.com/varkor/quiver/commit/4c8d50d1d045b360d81e28079b352859ab7b73a8, the Back/Forwards buttons are handled correctly by quiver. There still isn't support for updating the URL with every change, but I think this should satisfy your use case (you can save frequently manually). In the UI redesign (#20), I will probably add an option to save automatically.

I'm going to mark this issue as resolved, but let me know if this isn't a satisfactory solution.

**Comment by vikraman** [comment]
I tried it and it works great, thank you! I'll be pressing Ctrl+S after my edits often.
