### ISSUE TITLE
Logos on every embedded diagram?  We need an option to turn it off and have the click-back be the diagram itself.

### ISSUE THREAD

**Issue by enjoysmath** [varkor/quiver#131]
[My blog](https://enjoysmath.blogspot.com/2022/01/in-topos-every-map-x-xrightarrowf-omega.html?m=1)

Looks great, except that Quiver is advertised 3 times!  I would like to keep the link but have the link be the diagram itself, so the user can see the diagram as it looks on paper.

This is what I plan to do for Abstract Spacecraft link-backs to editor.   However, I'm not there yet, and am working on my blog now, and yeah... this feature is a must 😃

**Comment by varkor** [comment]
I will have a think about the best way to do this. I quite like having some indication that it is possible to open the diagram in **quiver**, but for smaller diagrams, the entire logo is quite a lot to include. Maybe it'd be better simply to include the "q".

**Comment by enjoysmath** [comment]
I would like to use your version of quiver if possible, so that it's always updated and embed it into a standalone desktop or mobile app using Qt/C++ and their method of communicating with the JS side.  Could we have an option without the logo?  I could credit your project in some other way?  Maybe an on-hover only logo at least, with a tooltip that says "open in Quiver in the browser."  This should have an external link symbol next to it (The box with an upward-right arrow exiting the box that's used on many websites).   Quiver is awesome!  I always mention it to many people.

**Comment by varkor** [comment]
@enjoysmath: sorry for taking so long to get to this. I've changed the behaviour in https://github.com/varkor/quiver/commit/8c154599b3bf6a8f8c697b3c985d3de262d61b7e so that the logo is hidden unless the user hovers over the diagram. It will be included in the next version of **quiver**, but it may not be released right away as there are a few other small changes I want to make first.

**Comment by enjoysmath** [comment]
Thanks @varkor
