### ISSUE TITLE
Upload quiver.sty to CTAN

### ISSUE THREAD

**Issue by obsgolem** [varkor/quiver#133]
Currently users of quiver must download quiver.sty in order to use it. It would be convenient if it was available via CTAN so that it could be automatically picked up via MikTex.

**Comment by varkor** [comment]
I have submitted the package to CTAN and will update this issue once the submission has been processed.

Edit: I need to create documentation for the `quiver.sty` package before it is accepted by CTAN. I hope to do so soon.

**Comment by varkor** [comment]
I intend to submit again this weekend.

**Comment by varkor** [comment]
I have resubmitted the package with documentation, and will update this issue once the submission as been processed.

**Comment by varkor** [comment]
The **quiver** package is [now available on CTAN](https://ctan.org/pkg/quiver).
