### ISSUE TITLE
Mode to disable rendering of diagrams

### ISSUE THREAD

**Issue by L1szt** [varkor/quiver#138]
Is there a possibility to disable the rendering of commutative diagrams (i.e. the rendering of `tikzcd` blocks in the document), similar to the draft mode for the graphics package?

**Comment by enjoysmath** [comment]
That's a good question.    But in general, we need a full-on API to talk to quiver.  Possibly even down to the level of overriding default buttons and replacing with our own site buttons.   I will look into doing this.   It simply just needs to be a JavaScript API  (i.e. a JS function that you call from HTML or JS) that enables/disables rendering mode for you, is that correct?  Or do you need it as URL parameters?

**Comment by L1szt** [comment]
@enjoysmath Thanks for the quick response. Ideally it would behave similarly to the `graphics` package, if I include it as `\usepackage[draft]{graphics}` instead of just `usepackage{graphics}` no images included via the `graphics` package get rendered/loaded when compiling the file.

**Comment by varkor** [comment]
**quiver** doesn't handle the actual rendering of the diagrams: this is really a TikZ feature. I would recommend asking on [Tex.SE](https://tex.stackexchange.com/) about how to disable rendering of inline TikZ diagrams in `draft` mode.
