### ISSUE TITLE
Decoding nodes from numbers

### ISSUE THREAD

**Issue by vikraman** [varkor/quiver#14]
In the exported LaTeX, the nodes are encoded using numbers. Quite often, I want to edit the exported LaTeX to tweak the diagram, rather than editing in quiver. Currently, it is a bit difficult to decode the text node from the vertex numbers. Would it be possible to do either of these two options?

- Not encode nodes using numbers. This could be an option in the export if no higher cells were used.
- Include the node-number mapping as a comment in the generated code.

**Comment by varkor** [comment]
I'm not opposed to this, but I would definitely rather focus on improving quiver to the point where editing the generated code directly is unnecessary.

**Comment by varkor** [comment]
Since https://github.com/varkor/quiver/issues/26, edges are now output on their own line. I think this makes the problem described in this issue less severe, because you can clearly read the name on each arrow. For example:
```latex
% https://varkor.github.io/quiver/?q=WzAsNCxbMCwwLCJcXGJ1bGxldCJdLFsyLDAsIlxcYnVsbGV0Il0sWzAsMSwiXFxidWxsZXQiXSxbMiwxLCJcXGJ1bGxldCJdLFswLDFdLFsyLDNdLFs0LDVdXQ==
\[\begin{tikzcd}
	{\bullet} && {\bullet} \\
	{\bullet} && {\bullet}
	\arrow[""{name=0}, from=1-1, to=1-3]
	\arrow[""{name=1}, from=2-1, to=2-3]
	\arrow[Rightarrow, from=0, to=1, shorten <=2mm, shorten >=2mm]
\end{tikzcd}\]
```
Does this help? It has a similar effect to including the mapping as comments in the source code.

**Comment by vikraman** [comment]
Oh yes, this is very helpful.

**Comment by varkor** [comment]
I shall close as solving the original problem, but feel free to reopen if you think this isn't sufficient.
