### ISSUE TITLE
Triple arrows don't render properly in tikz

### ISSUE THREAD

**Issue by pdehaye** [varkor/quiver#145]
This:
![image](https://user-images.githubusercontent.com/3274335/178612444-7d8d90a4-e1c9-4abd-bc45-2c3d8b75c350.png)

generates this code, which does not include the fact that this should be a triple arrow:

```
% https://q.uiver.app/?q=WzAsMixbMCwwLCJcXGJ1bGxldCJdLFsyLDAsIlxcYnVsbGV0Il0sWzAsMSwiIiwwLHsibGV2ZWwiOjN9XV0=
\[\begin{tikzcd}
	\bullet && \bullet
	\arrow[from=1-1, to=1-3]
\end{tikzcd}\]

```
Contrast with code for a double arrow:
```
% https://q.uiver.app/?q=WzAsMixbMCwwLCJcXGJ1bGxldCJdLFsyLDAsIlxcYnVsbGV0Il0sWzAsMSwiIiwwLHsibGV2ZWwiOjJ9XV0=
\[\begin{tikzcd}
	\bullet && \bullet
	\arrow[Rightarrow, from=1-1, to=1-3]
\end{tikzcd}\]
```

(`Rightarrow` signals as it should that this is a double arrow)

**Comment by varkor** [comment]
There's a warning message when you try to export a triple arrow:
<img width="1095" alt="image" src="https://user-images.githubusercontent.com/3943692/179213097-cc00d238-a9bf-47b5-8c83-f0689f139549.png">
This is tracked by https://github.com/varkor/quiver/issues/46.
