### ISSUE TITLE
Basic quality-of-life integration with some text editors

### ISSUE THREAD

**Issue by nullst** [varkor/quiver#148]
This is, at most, a "feature request" for project's readme rather than the application code. Or maybe a wiki page.

The URL embedded into the LaTeX export of a diagram provides a very convenient way to edit the diagram later. The only friction in the editing process is that you need to select the diagram's previous TeX code in your text editor to replace it with the new version, and this can become annoying if you tweak the same diagram multiple times in succession. I edit LaTeX in emacs, and I wrote a simple function that can be executed when the cursor is anywhere in the diagram's TeX code, which then selects the full text of the diagram and runs the browser with the corresponding URL. When I re-export new TeX code, I copy it, switch back to emacs, and paste it on top of the previous version. I found this function very pleasant to use, especially when bound to a hotkey.

The same customization could be made for any sufficiently programmable text editor, and should be simple to create. So if anyone can contribute corresponding code fragments for other editors (vim?), it would be nice.

Here's a basic emacs integration for q.uiver.app diagrams:

```elisp
(defun replace-quiver-diagram ()
  "Extracts the quiver URL from the diagram under cursor and runs it in browser. Selects the diagram."
  (interactive)
    (let ((start 0)
	  (end 0)
	  (url-start 0)
	  (url-end 0)
	  (url ""))
      (save-excursion
	(save-excursion
	  (re-search-backward "% https://q.uiver.app" nil)
	  (setq url-start (+ 2 (point)))
	  (beginning-of-line)
	  (setq start (point))
	(save-excursion
	  (re-search-forward "\\\\end{tikzcd}" nil)
	  (setq end (point)))
	(save-excursion
	  (goto-char url-start)
	  (re-search-forward "\n" nil)
	  (setq url-end (- (point) 1))
	  (skip-chars-forward " ")
	  ;; If the next two symbols after new line, up to whitespace,
	  ;; are "\[", modify the `end` value to be after \].
	  (when (string= "[" (string (char-after (+ 1 (point)))))
	      (setq end (+ 2 end))))
	(setq url (buffer-substring-no-properties url-start url-end))
	(start-process "" nil
		       ;; Edit this line to change the browser.
		       "flatpak" "run" "org.chromium.Chromium" url)))
      (goto-char start)
      (push-mark end t t)))

(add-hook 'TeX-mode-hook (lambda ()
			   (interactive)
			   (define-key TeX-mode-map (kbd "C-x q") 'replace-quiver-diagram)))
```

**Comment by varkor** [comment]
Thanks for sharing this – it's a nice idea! Let me think a little about how best to make this information available to people. Maybe a GitHub wiki would work best, as you suggest.

**Comment by varkor** [comment]
I've added a wiki page https://github.com/varkor/quiver/wiki/Editor-integration containing your extension, and added a link to the wiki from the README. It's quite minimal at the moment, but hopefully I can find time to expand it later.

Thanks for your contribution! Let me know if you'd prefer to be acknowledged differently on the wiki page.
