### ISSUE TITLE
I got Quiver embedded into a QtWidgets / C++ application.  How do I scale the font back to normal?

### ISSUE THREAD

**Issue by enjoysmath** [varkor/quiver#149]
![image](https://user-images.githubusercontent.com/1606391/203908239-174de36d-7830-4bbe-acae-b26d3ed3b174.png)

As you can see the font size is off.  What's the quickfix for this?

If anyone is interested in how to do this.   I can show you.  I'm making some sort of diagram chaser desktop app in which you will see many embedded diagrams on the screen like around 30 Quiver diagrams max.   You'll be able to drag and drop axioms, etc.  I will use boost's graph library for theorem I/O matching.

Currently I have Markdown + KaTeX + Quiver all driven from a Qt/C++ application.  To communicate you've got to learn some QWebChannel code.  But really I just adapted Qt's markdown example for this basic MWE.

**Comment by enjoysmath** [comment]
For the Quiver logo, I will keep it and maybe put a "Web" overlay on it.  So it, as well as the embed diagram code & link share, will link back to your hosted version.

**Comment by varkor** [comment]
The font size for labels is controlled here:
https://github.com/varkor/quiver/blob/6973c0605fe3b346f69d7cde1077d94fe6d57926/src/main.css#L395
I'm not sure why it would be so small in your context: perhaps there's another style that's overriding that one.
