### ISSUE TITLE
Advertise on the awesome-tikz list

### ISSUE THREAD

**Issue by vikraman** [varkor/quiver#15]
I think tikzcd-editor and quiver should be advertised on this awesome list.

https://github.com/xiaohanyu/awesome-tikz

**Comment by varkor** [comment]
I'm planning a big "advertising push" once #5, #6 and #10 are fixed. It could make sense to add quiver to that list as part of it.

(I would suggest suggestions regarding tikzcd-editor would be better made on its own repository 😉)

**Comment by varkor** [comment]
I've created a tracking issue (https://github.com/varkor/quiver/issues/22), which includes this, so I'm going to close this issue.
