### ISSUE TITLE
Support `renewcommand` and `DeclareMathOperator` in macros file

### ISSUE THREAD

**Issue by obsgolem** [varkor/quiver#152]
I want to use the same macros I use in my document(s) in quiver, but many of those macros are `renewcommand` or `DeclareMathOperator`. quiver appears to only load commands defined using `newcommand`, and thus fails to load these. See https://github.com/varkor/quiver/blob/8c154599b3bf6a8f8c697b3c985d3de262d61b7e/src/ui.js#L2993

**Comment by varkor** [comment]
Fixed in https://github.com/varkor/quiver/commit/d78995b13cba5e1195197e23d3f5f346e7d7dfab. This will be available in the next version of **quiver**, which I hope to release soon.
