### ISSUE TITLE
Do Quiver graphs generally have a canonical form?

### ISSUE THREAD

**Issue by enjoysmath** [varkor/quiver#154]
Was wondering, with all the arrows-to-arrows, arrows-to-object ability, can we canonicalize these graphs together with their labels?

I am actually needing this for a project.

**Comment by varkor** [comment]
In theory, it seems possible to decide upon a normal form for the graphs, but **quiver** doesn't currently do this (other than normalising some properties, like sorting objects by their position).

**Comment by enjoysmath** [comment]
What is that ordering?

Is it top top-to-bottom, left-to-right?

**Comment by varkor** [comment]
Top-to-bottom, then left-to-right.
