### ISSUE TITLE
Test out tikz-nfold with quiver

### ISSUE THREAD

**Issue by varkor** [varkor/quiver#158]
See https://github.com/jonschz/tikz-nfold.

**Comment by varkor** [comment]
The library appears to work nicely, and I plan to use it in **quiver** when it is a little more stable.

**Comment by jonschz** [comment]
Sounds great! By now I have implemented all the core features I wanted to have, and the list of known, fixable issues is very short (and only contains rare edge cases). Please let me know if you still miss features or experience bugs.

**Comment by varkor** [comment]
**quiver** will now make use of tikz-nfold when users make use of triple arrows or higher (https://github.com/varkor/quiver/commit/3ec01d7e419dc3f8dd22ebd725afa5e6551f06cf). Eventually, I plan to use tikz-nfold even for double arrows (#173). Thanks for your great library @jonschz, and for fixing the issues discovered during testing! This is going to make drawing higher-dimensional diagrams much simpler going forward 🎉
