### ISSUE TITLE
Is this change to the logo appropriate / within the license?

### ISSUE THREAD

**Issue by enjoysmath** [varkor/quiver#159]
![image](https://user-images.githubusercontent.com/1606391/230699222-06a9ac85-8cc1-478d-8e94-c172868d8625.png)

That's Quiver embedded as an iframe into a Bootstrap 5 page.   I changed the logo to "Quiver (powered editing)" so that I wouldn't have to edit the code just for that, but also I would like to let the users know about your project :)

**Comment by varkor** [comment]
**quiver** uses the [MIT licence](https://github.com/varkor/quiver/blob/master/LICENSE), so yes.
