### ISSUE TITLE
history.pushState({}, ...    :::   Shouldn't it be ui.history.pushState({}, ... )?

### ISSUE THREAD

**Issue by enjoysmath** [varkor/quiver#160]
```
        add_action(
            "Save",
            [{ key: "S", modifier: true, context: Shortcuts.SHORTCUT_PRIORITY.Always }],
            () => {
                const { data } = ui.quiver.export(
                    "base64",
                    ui.settings,
                    ui.options(),
                    ui.definitions(),
                );
                // `data` is the new URL.
                history.pushState({}, "", data);
            },
        );
```

I ask, because I'm currently copy/pasting that code into a quiver_interface.js file I'm using to override some of the buttons.

I think it should be ui.history...  I see no history = ... anywhere in the ui.js file so...

Thanks @varkor !!!

EnjoysMath

**Comment by varkor** [comment]
This `history` is not `ui.history`, but the global object [`history`](https://developer.mozilla.org/en-US/docs/Web/API/Window/history).

**Comment by enjoysmath** [comment]
@varkor  Where is that `history` global declared?  I'm having trouble finding it anywhere even with textual search.

**Comment by varkor** [comment]
It's defined by the browser: click on the hyperlink in my previous message for the documentation.
