### ISSUE TITLE
Redo keyboard shortcut doesn't work

### ISSUE THREAD

**Issue by vikraman** [varkor/quiver#17]
Ctrl+Shift+Z doesn't seem to work for me, but the Redo button works. Ctrl+Z and Undo buttons work. I was able to reproduce it on both chrome and firefox.

**Comment by vikraman** [comment]
Actually this is very strange, sometimes Ctrl+Z also stops working while editing.

**Comment by varkor** [comment]
Fixed in https://github.com/varkor/quiver/commit/197bf65e2d0791cb1be9aa624cc1892dc292c620. I couldn't see why Control-Z would not work, so if you keep encountering this problem, please do open another issue for it.
