### ISSUE TITLE
Modifier key conflict in MacOS

### ISSUE THREAD

**Issue by Tevqoon** [varkor/quiver#170]
Currently, in the interface and shortcuts menu only ⌘ is listed as a valid modifier for certain keyboard shortcuts, but control still works. This makes it is impossible to use certain built in MacOS commands, such as control+E to jump to the end of the line, as it opens the export to LaTeX menu. It would be nice to either turn off control as a valid modifier on MacOS or make it an option to use only command.

**Comment by varkor** [comment]
Thanks for the feedback. I've disabled control on Apple platforms in https://github.com/varkor/quiver/commit/0377991c40057b5ad58eb895a8d00105ac326456, which will be available in the next release of **quiver**.
