### ISSUE TITLE
Loading order between xcolor and quiver

### ISSUE THREAD

**Issue by Spamakin** [varkor/quiver#175]
It should be documented somewhere that `quiver` should be loaded before `xcolor`. Specifically I am running into issues if I load `quiver` before `xcolor` as such
```tex
\usepackage{quiver}
\usepackage[dvipsnames,usenames,cmyk]{xcolor}
```

**Comment by varkor** [comment]
Do you mean `quiver` should be loaded *after* `xcolor`? I think this would make sense, since `quiver` loads `tikz` (via `tikz-cd`), which loads `xcolor` itself, and so the package options might clash.

**Comment by Spamakin** [comment]
Yea I was saying that the order I pasted above caused issues. This should maybe be documented somewhere. I couldn't find anything in the `README` or any other documentation.
