### ISSUE TITLE
Export to LateX but display the gridline (boxes)

### ISSUE THREAD

**Issue by ouboub** [varkor/quiver#181]
Hi

I am using quiver now for some weeks, and it is very useful.
I can't find that option:
is it possible when exporting to LateX  to have the gridlines displayed?
right now I only see the content of the boxes and the arrows between them, but not the grid lines.

thanks

Uwe Brauer

**Comment by varkor** [comment]
It's not possible to export a diagram with gridlines: the grid is just there to make it more convenient to edit the diagram. Commutative diagrams are generally not drawn with a grid. I don't expect to support this feature, as it seems uncommon. However, I expect it is possible to do with TikZ (you could ask on [TeX.SE](https://tex.stackexchange.com/) if you are unsure how to do it).

**Comment by ouboub** [comment]
> It's not possible to export a diagram with gridlines: the grid is just there to make it more convenient to edit the diagram. Commutative diagrams are generally not drawn with a grid. I don't expect to support this feature, as it seems uncommon. However, I expect it is possible to do with TikZ (you could ask on [TeX.SE](https://tex.stackexchange.com/) if you are unsure how to do it).

Ok I see, the diagrams I produce with quiver, consist of equations, whose logical relation I indicate with 
arrows. Is there any way to have boxes around these equations by quiver?

**Comment by ouboub** [comment]
> > It's not possible to export a diagram with gridlines: the grid is just there to make it more convenient to edit the diagram. Commutative diagrams are generally not drawn with a grid. I don't expect to support this feature, as it seems uncommon. However, I expect it is possible to do with TikZ (you could ask on [TeX.SE](https://tex.stackexchange.com/) if you are unsure how to do it).
> 
> Ok I see, the diagrams I produce with quiver, consist of equations, whose logical relation I indicate with arrows. Is there any way to have boxes around these equations by quiver?

to answer my own question:
```
\boxed{
  \begin{aligned}
 &    \int\limits_{\mathbb{T}^{3}}^{} e^{\pmb{\kappa}\Omega t}\left( e^{\pmb{\kappa}\Omega t}\partial_t\Phi - \bar{\Psi} \right)m^{ab}\partial_a\partial_{b}\Phi d^3x                                  \\
 &=
      -       \int\limits_{\mathbb{T}^{3}}^{} e^{\pmb{\kappa}\Omega t}\left( e^{\pmb{\kappa}\Omega t}\partial_t\Phi-\bar{\Psi}  \right)\partial_a \left( m^{ab} \right)          \partial_{b}\Phi d^3x \\
 &-       \int\limits_{\mathbb{T}^{3}}^{} e^{\pmb{\kappa}\Omega t}\left( e^{\pmb{\kappa}\Omega t}  \right)m^{ab} \partial_a \left(\partial_t\Phi  \right)          \partial_{b}\Phi d^3x
  \end{aligned}
}
```
does the trick
