### ISSUE TITLE
Navigate to end of line, in a mathematical expression

### ISSUE THREAD

**Issue by ouboub** [varkor/quiver#182]
Hi
It turns out that I want to surround by a box using 
```
\boxed{}
```
Now, the formulas are quite long so to reach the end of such a formula, I have to press the right arrow for quite some time.
Is there any key-binding I miss, that would allow me to jump to the end of the line?
Thanks
Uwe Brauer

**Comment by varkor** [comment]
You should be able to press the End key on your keyboard (on macOS you can press ⌘→, and there are probably similar shortcuts on other operating systems).

**Comment by ouboub** [comment]
thanks, this worked! Maybe add it to the keybinding information?

**Comment by varkor** [comment]
This isn't a **quiver**-specific shortcut, by the way: it should work on any text input. So far, I've only listed **quiver**-specific shortcuts in the key bindings window (otherwise there would just be too many to list).
