### ISSUE TITLE
query replace in latex expression?

### ISSUE THREAD

**Issue by ouboub** [varkor/quiver#184]
Hi,

I have to write a new diagram based on an old one, and one of the changes is to replace
\Phi by \Theta

(I don't want to redefine it via a macro)

is there any chance to get a query-replace function?
right now I have to edit every box.
thanks
uwe Brauer

**Comment by varkor** [comment]
You can replace the text in a text editor, import it into **quiver** via the "Import tikz-cd" button, and then export it to LaTeX again. I'm not likely to add a native search-and-replace feature to **quiver** because it would be a fair amount of work.

**Comment by ouboub** [comment]
ok fair enough, but where is this button, I can't find it, nor can I find it in the keybinding menu

**Comment by varkor** [comment]
<img width="180" alt="image" src="https://github.com/varkor/quiver/assets/3943692/5168180a-9acf-470a-a97d-24c60870732a">

It's at the bottom of the page, next to the export buttons. If you don't see it, you may need to clear your cache and refresh the page.

**Comment by ouboub** [comment]
hm I installed quiver on my machine (a month ago, so it should be recent)
here is what I see
![quiver](https://github.com/varkor/quiver/assets/5957203/93444793-ff4e-4b01-8ec4-b37d1d8a0444)

**Comment by ouboub** [comment]
oh I see, I can see this button on the website but not on my local machine, 
I am using commit
```
2d222aaa21d75290be07256551f244a38e45f653
```

**Comment by ouboub** [comment]
ok I pulled and recompiled, problem solve thanks
