### ISSUE TITLE
MathJax font \mathbb

### ISSUE THREAD

**Issue by analytic-bias** [varkor/quiver#194]
Some blackboard bold fonts are not displayed properly.

Try: Put `\mathbb{1}` into a cell:
![image](https://github.com/varkor/quiver/assets/6694864/11a84ab0-0528-4d32-a9b1-a24196df758e)

It's supposed to look at: 𝟙.

**Comment by varkor** [comment]
`mathbb` is defined by the `amsfonts` package, which does not provide symbols for blackboard bold numbers or lowercase letters. There are other packages that define such symbols, but they are not yet supported by KaTeX (https://github.com/KaTeX/KaTeX/issues/473). So this behaviour is expected for now (at least until KaTeX adds support for them).
