### ISSUE TITLE
Local version of q.uiver?

### ISSUE THREAD

**Issue by clafond1** [varkor/quiver#199]
I love the q.uiver website, but I was wondering if there is a way to get the application to run on my laptop locally, like without the need for an internet connection. I am not particularly well versed in using make files to build apps (perhaps this is even the wrong way to say it), so I was just wondering if there is a step by step guide on what to do once I download Makefile.txt?

**Comment by ouboub** [comment]
> I love the q.uiver website, but I was wondering if there is a way to get the application to run on my laptop locally, like without the need for an internet connection. I am not particularly well versed in using make files to build apps (perhaps this is even the wrong way to say it), so I was just wondering if there is a step by step guide on what to do once I download Makefile.txt?

that is extremly simple, I did several month ago and it is worth the effort.

- use 
```
git clone git@github.com:varkor/quiver.git
```
then run make, it will automatically download and compile everything (I am on Ubuntu)

supposed you cloned this repository to 
```
/home/onlyme/src/quiver
```
and compiled, then

open any modern browser
select open file and chose
/home/onlyme/src/quiver/src/index.html

that is all, use a bookmark to remember, enjoy
/home/onlyme/src/quiver

**Comment by varkor** [comment]
Thanks for explaining, @ouboub!

It will soon be much easier to run **quiver** locally, once #176 is merged. After that, it will only be necessary to have opened **quiver** at least once when online, and then you will be able to use it offline subsequently. I hope to merge this feature and push a new version of **quiver** soon.
