### ISSUE TITLE
Color definition in macro file seems not to work

### ISSUE THREAD

**Issue by ouboub** [varkor/quiver#201]
Hi

I put my local compiled quiver in a directory my local Apache Server can read and load the following macro file
via http://localhost/quiver/src/style/quiver-macros.sty
```
\ProvidesPackage{quiver-macros}[2023/10/12 oub]
\newcommand{\farbboxed}[2]{\fcolorbox{black}{#1}{$\displaystyle#2$}}
\usepackage{xcolor}
\definecolor{DarkOrange}{rgb}{1.000000,0.549020,0.000000}
\definecolor{orange}{RGB}{255,127,0}
\definecolor{Lightorange}{HTML}{FAA21A}
\definecolor{Melon}{HTML}{F89E7B}
\definecolor{Melon}{RGB}{16.8,229.3,185.5}
\definecolor{Melon}{rgb}{0.972549,0.619607,0.482352}
```
however the color Melon is not displayed I tried HEX and rgb
what do I miss?

**Comment by varkor** [comment]
If you open the colour palette, you will see that the colour has been loaded:
<img width="544" alt="image" src="https://github.com/varkor/quiver/assets/3943692/e7c0577c-2ddf-4659-8c3a-97cb191fef6f">
However, it's not currently possible to use custom colours using commands like `\color`, etc. You can only use the colours from the colour palette. This is due to a limitation in KaTeX (#202).

Note that you cannot use the `HTML` colour format yet in **quiver**, not are decimal points accepted in the `RGB` specification. It's also not necessary to use `\ProvidesPackage` or `\usepackage{xcolor}` (though it's also harmless to write them). E.g. you could just use:
```latex
\newcommand{\farbboxed}[2]{\fcolorbox{black}{#1}{$\displaystyle#2$}}
\definecolor{DarkOrange}{rgb}{1.000000,0.549020,0.000000}
\definecolor{orange}{RGB}{255,127,0}
\definecolor{Melon}{rgb}{0.972549,0.619607,0.482352}
```

**Comment by ouboub** [comment]
> If you open the colour palette, you will see that the colour has been loaded: <img alt="image" width="544" src="https://private-user-images.githubusercontent.com/3943692/290104011-e7c0577c-2ddf-4659-8c3a-97cb191fef6f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDI0NTg5NjMsIm5iZiI6MTcwMjQ1ODY2MywicGF0aCI6Ii8zOTQzNjkyLzI5MDEwNDAxMS1lN2MwNTc3Yy0yZGRmLTQ2NTktOGMzYS05N2NiMTkxZmVmNmYucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQUlXTkpZQVg0Q1NWRUg1M0ElMkYyMDIzMTIxMyUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyMzEyMTNUMDkxMTAzWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9N2FmNDJjNjY1MTY0NTUzNjVmODM1MDk2MDg4MGViNGY2NDE4MzI5MGM2YzFmZDc4MmIyMTEzNmQ0ZTY0YWFlNyZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.IZMBGA7BYY8BobfnMUXPlTCH7OkQBrWEvzeCbs9nRsE"> However, it's not currently possible to use custom colours using commands like `\color`, etc. You can only use the colours from the colour palette. This is due to a limitation in KaTeX (#202).
> 
> Note that you cannot use the `HTML` colour format yet in **quiver**, not are decimal points accepted in the `RGB` specification. It's also not necessary to use `\ProvidesPackage` or `\usepackage{xcolor}` (though it's also harmless to write them). E.g. you could just use:
> 
> ```
> \newcommand{\farbboxed}[2]{\fcolorbox{black}{#1}{$\displaystyle#2$}}
> \definecolor{DarkOrange}{rgb}{1.000000,0.549020,0.000000}
> \definecolor{orange}{RGB}{255,127,0}
> \definecolor{Melon}{rgb}{0.972549,0.619607,0.482352}
> ```

thanks for this explanation, in that case, I will then stick to the predefined colors,
since the diagram I produce is not going to be published anywhere
