### ISSUE TITLE
Is there a way to show a bijection in the editor?

### ISSUE THREAD

**Issue by jamesnelmore** [varkor/quiver#212]
I would like to show a transformation is bijective by placing $\sim$ above the corresponding arrow and the name of the transformation beneath the arrow. I have done this by centering the label and using a newline, however I am hoping there is a more elegant way to do this.

**Comment by varkor** [comment]
At the moment, multiple labels are not supported natively (see #92 for the dedicated issue). The most convenient way to achieve what you want is to draw a normal arrow with the usual label, then draw another invisible arrow over the top (i.e. by using the empty tail, body, and head options) in **quiver**, with the `~` label. This should have better spacing than using a label with a newline.
