### ISSUE TITLE
How should I add a unitary morphism of one object in the quiver?

### ISSUE THREAD

**Issue by BHanZhang** [varkor/quiver#215]
How should I add a unitary morphism of one object in the quiver? I want to add a unitary morphism $\mathrm{id}_X$ of objext $X$ like this:
<img width="169" alt="截屏2024-03-19 16 50 20" src="https://github.com/varkor/quiver/assets/78583665/f2ba7e0d-eeff-4876-80f7-0e97f46b5e05">

**Comment by varkor** [comment]
There is an open feature request for adding loops here: #31. I have not found time to work on this recently. For now, the simplest solution is to modify the TikZ that **quiver** exports and add a loop in manually, though I appreciate this is not particularly convenient.
