### ISSUE TITLE
Cannot import vertical composition as latex

### ISSUE THREAD

**Issue by thwfhk** [varkor/quiver#221]
Hi, I wanted to draw a vertical composition of natural transformations in quiver and import it as latex. However, the website just got stuck when importing. I tried to build an older version of quiver on my computer and found that 1.4.1 seems to be the newest version that can import vertical composition as latex.

Here is my MWE: https://q.uiver.app/#q=WzAsMixbMCwwLCJcXGJ1bGxldCJdLFsyLDAsIlxcYnVsbGV0Il0sWzAsMV0sWzAsMSwiIiwyLHsiY3VydmUiOjN9XSxbMCwxLCIiLDEseyJjdXJ2ZSI6LTN9XSxbMiwzLCIiLDEseyJzaG9ydGVuIjp7InNvdXJjZSI6MjAsInRhcmdldCI6MjB9fV0sWzQsMiwiIiwxLHsic2hvcnRlbiI6eyJzb3VyY2UiOjIwLCJ0YXJnZXQiOjIwfX1dXQ==

It got stuck when clicking the LaTex button.

**Comment by varkor** [comment]
Thank you for reporting this issue – I accidentally broke exporting 2-cells in the latest version and hadn't realised. I've pushed a fix (https://github.com/varkor/quiver/commit/0d07e9a15cbd9f6005d20a2bc82422aadbfc36e2), so it should work again. Let me know if it still doesn't work as expected.
