### ISSUE TITLE
Include installation instructions for TikZ libraries

### ISSUE THREAD

**Issue by ncfavier** [varkor/quiver#231]
In addition to listing the required TikZ libraries, it would be nice to include the installation command (e.g. `\usetikzlibrary{nfold}`) so that people don't need to remember how to install TikZ libraries (I was trying `\usepackage{tikz-nfold}`...)

**Comment by varkor** [comment]
**quiver** links to the CTAN page for `tikz-nfold`, whose documentation explains how to use it. My feeling is that if **quiver** suggested the command `\usetikzlibrary{nfold}`, people may try it without having the package installed, and then be confused when it doesn't work.

**Comment by ncfavier** [comment]
That's fair enough.
