### ISSUE TITLE
Cannot move Curve etc. sliders on iOS

### ISSUE THREAD

**Issue by eric-downes** [varkor/quiver#233]
On the UI panel, there are sliders: Position, Offset, Curve, etc. that affect a selected arrow.

It is possible to tap the circular slider on my ipad, which is where I often draw diagrams; it turns gray momentarily, but it is not possible to actually move it left or right.  Interpreting the gesture is too complex, I suppose.  So my poor arrows, they are all straight and (co)limits of diagrams look sad.

I don't know enough js/css to be of much help here.  It seems like some UX folks may have solved this problem; perhaps its possible to import their solution?
https://github.com/zingchart/zingtouch

Thanks again for making quiv.er!  Happy to post screenshots or test betas etc. if that would help.

**Comment by varkor** [comment]
This bug must have been introduced when I reworked sliders to support multi-thumb sliders. I'll look into it, thanks for reporting.

**Comment by varkor** [comment]
I believe this has been fixed in https://github.com/varkor/quiver/commit/ee29f53d03d2e61b1a6a4f4edb686a259d56c1ed. Would you be able to try the update out at https://q.uiver.app/dev/ and confirm that it is working for you now?

**Comment by eric-downes** [comment]
Success!  Thank you very much!

**Comment by eric-downes** [comment]
(sorry, maybe I should have let you PR to master before closing; in any case thanks again.)

**Comment by varkor** [comment]
Great :) I'll try to push a minor release tomorrow.
