### ISSUE TITLE
"labels" on arrows not produces error

### ISSUE THREAD

**Issue by klonedrekt** [varkor/quiver#236]
I am probably just being silly, but for some reason I get the error "undefined control sequence" when adding labels to the arrows. The arrows by themselves work just fine, but the moment I add a label I get an error. What is the mistake that I am making? Thank you!

**Comment by varkor** [comment]
Can you list exactly the steps you are taking to produce the error, and a screenshot of the error? Thanks!

**Comment by klonedrekt** [comment]
I just resolved it: something to do with using the babel package (on german). After removing that from the preamble everything goes smoothly.
