### ISSUE TITLE
LaTeX result is too different from webpage

### ISSUE THREAD

**Issue by UlyssesZh** [varkor/quiver#237]
[Example](https://q.uiver.app/?q=WzAsMTEsWzIsMCwiVyJdLFswLDIsIldeeygxKX0iXSxbNCwyLCJXXnsoMil9Il0sWzAsNCwiV157XFxwZXJwKDEpfSJdLFs0LDQsIldee1xccGVycCgyKX0iXSxbMCw2LCJcXHZlYyBXXntcXHBhcmFsbGVsKDEpfSJdLFs0LDYsIlxcdmVjIFdee1xccGFyYWxsZWwoMil9Il0sWzIsOCwiXFx2ZWMgV15cXHBhcmFsbGVsIl0sWzIsMTAsIldeXFxwZXJwIl0sWzEsMTEsIlxcdmVjIFdee1xccGVycFxccGFyYWxsZWx9Il0sWzMsMTEsIldee1xccGVycFxccGVycH0iXSxbMSwyLCJcXHRpbWVzIiwyLHsiY3VydmUiOi00LCJzdHlsZSI6eyJoZWFkIjp7Im5hbWUiOiJub25lIn19fV0sWzEsNCwiXFx0aW1lcyIsMCx7ImN1cnZlIjo1LCJzdHlsZSI6eyJoZWFkIjp7Im5hbWUiOiJub25lIn19fV0sWzMsMiwiXFx0aW1lcyIsMCx7ImN1cnZlIjo1LCJzdHlsZSI6eyJoZWFkIjp7Im5hbWUiOiJub25lIn19fV0sWzMsNCwiXFx0aW1lcyIsMCx7ImN1cnZlIjo1LCJzdHlsZSI6eyJoZWFkIjp7Im5hbWUiOiJub25lIn19fV0sWzksMTAsIisiLDIseyJjdXJ2ZSI6LTEsInN0eWxlIjp7ImhlYWQiOnsibmFtZSI6Im5vbmUifX19XSxbNSw2LCJcXHZlY1xccmhvIiwyLHsiY3VydmUiOjMsInN0eWxlIjp7ImJvZHkiOnsibmFtZSI6ImJhcnJlZCJ9fX1dLFs3LDUsIlxcdmVjIGNeeygxKX0iLDAseyJjdXJ2ZSI6LTEsInN0eWxlIjp7ImJvZHkiOnsibmFtZSI6ImJhcnJlZCJ9fX1dLFs3LDYsIlxcdmVjIGNeeygyKX0iLDIseyJjdXJ2ZSI6MSwic3R5bGUiOnsiYm9keSI6eyJuYW1lIjoiYmFycmVkIn19fV0sWzcsOCwiKyIsMCx7ImN1cnZlIjo0LCJzdHlsZSI6eyJoZWFkIjp7Im5hbWUiOiJub25lIn19fV0sWzQsNiwiKyIsMix7ImN1cnZlIjotMiwic3R5bGUiOnsiaGVhZCI6eyJuYW1lIjoibm9uZSJ9fX1dLFszLDUsIisiLDAseyJjdXJ2ZSI6Miwic3R5bGUiOnsiaGVhZCI6eyJuYW1lIjoibm9uZSJ9fX1dLFs1LDYsIlxcdGltZXMvKyIsMCx7InN0eWxlIjp7ImhlYWQiOnsibmFtZSI6Im5vbmUifX19XSxbMCw4LCJcXHBpIiwwLHsiY3VydmUiOi01fV0sWzUsOSwiXFx2ZWNcXHBpIiwyLHsiY3VydmUiOjMsInN0eWxlIjp7ImJvZHkiOnsibmFtZSI6ImJhcnJlZCJ9fX1dLFs2LDksIlxcdmVjXFxwaSIsMCx7ImN1cnZlIjotNSwic3R5bGUiOnsiYm9keSI6eyJuYW1lIjoiYmFycmVkIn19fV0sWzEsMywiXFxwaV57KDEpfSJdLFsyLDQsIlxccGleeygyKX0iXSxbMTEsMCwiIiwwLHsibGV2ZWwiOjF9XSxbMTIsOCwiXFxwaSIsMCx7ImN1cnZlIjoxLCJsZXZlbCI6MSwic3R5bGUiOnsiYm9keSI6eyJuYW1lIjoiYmFycmVkIn19fV0sWzEzLDgsIlxccGkiLDAseyJjdXJ2ZSI6LTEsImxldmVsIjoxLCJzdHlsZSI6eyJib2R5Ijp7Im5hbWUiOiJiYXJyZWQifX19XSxbMTQsMTAsIlxccGkiLDIseyJjdXJ2ZSI6LTMsImxldmVsIjoxLCJzdHlsZSI6eyJib2R5Ijp7Im5hbWUiOiJiYXJyZWQifX19XSxbMTUsOCwiIiwyLHsibGV2ZWwiOjF9XSxbMTksMCwiIiwwLHsiY3VydmUiOi0zLCJsZXZlbCI6MX1dLFsyMCwyLCIiLDIseyJjdXJ2ZSI6MywibGV2ZWwiOjF9XSxbMjEsMSwiIiwyLHsiY3VydmUiOi0zLCJsZXZlbCI6MX1dLFsyMiw5LCJcXHZlY1xccGkiLDIseyJjdXJ2ZSI6NCwibGV2ZWwiOjF9XV0=&embed)

Webpage result:
![Screenshot_20231118-094051_Firefox.jpg](https://github.com/varkor/quiver/assets/26196187/68111633-d476-41d9-b055-99e169d325c0)

LaTeX result:
![test](https://github.com/varkor/quiver/assets/26196187/36bde87f-3b9f-4516-9bcb-9ea51c5d1272)

<details><summary>LaTeX codes</summary>

```tex
\documentclass{standalone}
\usepackage{quiver}
\begin{document}
$\displaystyle\begin{tikzcd}
	&& W \\
	\\
	{W^{(1)}} &&&& {W^{(2)}} \\
	\\
	{W^{\perp(1)}} &&&& {W^{\perp(2)}} \\
	\\
	{\vec W^{\parallel(1)}} &&&& {\vec W^{\parallel(2)}} \\
	\\
	&& {\vec W^\parallel} \\
	\\
	&& {W^\perp} \\
	& {\vec W^{\perp\parallel}} && {W^{\perp\perp}}
	\arrow["\pi", curve={height=-30pt}, from=1-3, to=11-3]
	\arrow[""{name=0, anchor=center, inner sep=0}, "\times"', curve={height=-24pt}, no head, from=3-1, to=3-5]
	\arrow["{\pi^{(1)}}", from=3-1, to=5-1]
	\arrow[""{name=1, anchor=center, inner sep=0}, "\times", curve={height=30pt}, no head, from=3-1, to=5-5]
	\arrow["{\pi^{(2)}}", from=3-5, to=5-5]
	\arrow[""{name=2, anchor=center, inner sep=0}, "\times", curve={height=30pt}, no head, from=5-1, to=3-5]
	\arrow[""{name=3, anchor=center, inner sep=0}, "\times", curve={height=30pt}, no head, from=5-1, to=5-5]
	\arrow[""{name=4, anchor=center, inner sep=0}, "{+}", curve={height=12pt}, no head, from=5-1, to=7-1]
	\arrow[""{name=5, anchor=center, inner sep=0}, "{+}"', curve={height=-12pt}, no head, from=5-5, to=7-5]
	\arrow["{\vec\rho}"', "\shortmid"{marking}, curve={height=18pt}, from=7-1, to=7-5]
	\arrow[""{name=6, anchor=center, inner sep=0}, "{\times/+}", no head, from=7-1, to=7-5]
	\arrow["{\vec\pi}"', "\shortmid"{marking}, curve={height=18pt}, from=7-1, to=12-2]
	\arrow["{\vec\pi}", "\shortmid"{marking}, curve={height=-30pt}, from=7-5, to=12-2]
	\arrow["{\vec c^{(1)}}", "\shortmid"{marking}, curve={height=-6pt}, from=9-3, to=7-1]
	\arrow["{\vec c^{(2)}}"', "\shortmid"{marking}, curve={height=6pt}, from=9-3, to=7-5]
	\arrow[""{name=7, anchor=center, inner sep=0}, "{+}", curve={height=24pt}, no head, from=9-3, to=11-3]
	\arrow[""{name=8, anchor=center, inner sep=0}, "{+}"', curve={height=-6pt}, no head, from=12-2, to=12-4]
	\arrow[from=0, to=1-3]
	\arrow["\pi", "\shortmid"{marking}, curve={height=6pt}, from=1, to=11-3]
	\arrow[curve={height=-18pt}, from=4, to=3-1]
	\arrow["\pi", "\shortmid"{marking}, curve={height=-6pt}, from=2, to=11-3]
	\arrow["\pi"', "\shortmid"{marking}, curve={height=-18pt}, from=3, to=12-4]
	\arrow[curve={height=18pt}, from=5, to=3-5]
	\arrow["{\vec\pi}"', curve={height=24pt}, from=6, to=12-2]
	\arrow[curve={height=-18pt}, from=7, to=1-3]
	\arrow[from=8, to=11-3]
\end{tikzcd}$
\end{document}
```

</details>

We cannot blame KaTeX because this is mostly layout problem.

**Comment by varkor** [comment]
**quiver** currently relies on various heuristics to produce tikz-cd code that reproduces the appearance of diagrams in the editor. Unfortunately, these are not perfect. There are some improvements that can be made (see #46 and #111), but ultimately the best solution would be to switch away from tikz-cd to TikZ. This would be a large project, though. For now, I'll close in favour of #46.
