### ISSUE TITLE
Missing Keybind

### ISSUE THREAD

**Issue by ccatrett** [varkor/quiver#238]
What is the keybinding for the option indicated by the red circle? I couldn't find it on github or in any of the shortcuts. This occurs on both the app and the website. 

<img width="951" alt="quiver_missing_keybind" src="https://github.com/varkor/quiver/assets/144408828/195ef60b-dd9e-4ac6-9b2b-48c04731a4e2">

**Comment by varkor** [comment]
I didn't add a shortcut for this button, because it may be reproduced by pressing <kbd>V</kbd><kbd>F</kbd>.
