### ISSUE TITLE
Generalize the adjunction option to additional symbols

### ISSUE THREAD

**Issue by GeoffreySangston** [varkor/quiver#248]
I'm currently using the adjunction option as a hack to produce arrows labeled with \dashv. E.g.,

`\arrow["\dashv"{anchor=center}, draw=none, from=6-4, to=6-5]`

Then when I export, I change '\dashv' to '\approx' or '\subset'. I'm not sure if this is considered bad form, and perhaps that is why additional symbols like 'approx' and 'subset' are not supported. If not, it could be more convenient if the system allowed me to select a replacement for dashv from a list of options (=, \subset, \approx, etc..),
or to allow me to arbitrarily change \dashv to a different latex command.

quiver is a brilliant tool by the way. Thanks!

**Comment by varkor** [comment]
At the moment, my approach is to simply draw an arrow with no heady/body/tail and use a centre-aligned label, but it could be useful to make this more convenient, as it currently takes a few clicks to achieve this.

**Comment by GeoffreySangston** [comment]
It's not really an issue then. I raised the issue only because I didn't think of that solution. Essentially I misled myself because I assumed the presence of a built-in option for the adjunction symbol meant that was the only possibility.
