### ISSUE TITLE
Update README with local build instructions

### ISSUE THREAD

**Issue by varkor** [varkor/quiver#256]
**quiver** must now run via localhost, but this is not currently mentioned in the README.

**Comment by varkor** [comment]
Fixed by #255.

**Comment by FruitfulApproach** [comment]
I have no problem embedding Quiver into my Django site.  It runs via any hosting configuration, except for iframe's it's good news that I'm serving from the same host.  Runs locally in my debug environment but equally well when hosted on Heroku...  I also embedded it into a Qt/C++ widget before.
