### ISSUE TITLE
Error: 'The saved diagram was malformed and could not be loaded.' when clicking the Quiver logo on embedded content

### ISSUE THREAD

**Issue by rishubil** [varkor/quiver#259]
Clicking the Quiver logo on the bottom-left corner of embedded content results in the error: `The saved diagram was malformed and could not be loaded.`

This may be due to improper encoding of the URL parameters.

The embed URL where this error occurs is as follows:

https://q.uiver.app/#q=WzAsNyxbMCwxLCJcXGJlZ2lue3BtYXRyaXh9WFxcZW5ke3BtYXRyaXh9IFxcYmVnaW57Ym1hdHJpeH0/XFxlbmR7Ym1hdHJpeH0iXSxbMSwwLCJcXGJlZ2lue3BtYXRyaXh9WF57LTF9L1hcXGVuZHtwbWF0cml4fSBcXGJlZ2lue2JtYXRyaXh9P1xcZW5ke2JtYXRyaXh9Il0sWzEsMSwiXFxiZWdpbntwbWF0cml4fVheey0yfS9YXFxlbmR7cG1hdHJpeH0gXFxiZWdpbntibWF0cml4fT9cXGVuZHtibWF0cml4fSJdLFsxLDIsIlxcYmVnaW57cG1hdHJpeH1YXnstM30vWFxcZW5ke3BtYXRyaXh9IFxcYmVnaW57Ym1hdHJpeH0/XFxlbmR7Ym1hdHJpeH0iXSxbMiwwLCJcXGJlZ2lue3BtYXRyaXh9WF57LTJ9L1heey0xfS9YXFxlbmR7cG1hdHJpeH0gXFxiZWdpbntibWF0cml4fT9cXGVuZHtibWF0cml4fSJdLFsyLDEsIlxcYmVnaW57cG1hdHJpeH1YXnstNH0vWF57LTJ9L1hcXGVuZHtwbWF0cml4fSBcXGJlZ2lue2JtYXRyaXh9P1xcZW5ke2JtYXRyaXh9Il0sWzMsMSwiXFxiZWdpbntwbWF0cml4fVgtXFxlbmR7cG1hdHJpeH0gXFxiZWdpbntibWF0cml4fT9cXGVuZHtibWF0cml4fSJdLFszLDYsIlxcY2hhclwiMjQ2OCIsMCx7ImN1cnZlIjoyfV0sWzEsNCwiXFxjaGFyXCIyNDYzIl0sWzQsNiwiXFxjaGFyXCIyNDY2IiwwLHsiY3VydmUiOi0xfV0sWzIsNCwiXFxjaGFyXCIyNDY0IiwxLHsiY3VydmUiOi0xLCJzdHlsZSI6eyJib2R5Ijp7Im5hbWUiOiJkYXNoZWQifX19XSxbMiw1LCJcXGNoYXJcIjI0NjUiXSxbNSw2LCJcXGNoYXJcIjI0NjciXSxbMCwxLCJcXGNoYXJcIjI0NjAiLDAseyJjdXJ2ZSI6LTF9XSxbMCwyLCJcXGNoYXJcIjI0NjEiXSxbMCwzLCJcXGNoYXJcIjI0NjIiLDIseyJjdXJ2ZSI6MX1dXQ==&embed

**Comment by varkor** [comment]
Thanks for reporting. The issue appears to be that there is a `/` in the URL, and this is getting decoded incorrectly.

**Comment by varkor** [comment]
Fixed in https://github.com/varkor/quiver/commit/f05f96b58ad63709da58a33d305b74a53308c077, which will be available in the next version of **quiver**.
