### ISSUE TITLE
Show 2-arrow while drawing

### ISSUE THREAD

**Issue by vikraman** [varkor/quiver#28]
This is a very minor nitpick that I just noticed. 

While drawing an arrow starting at a node, a 1-arrow is shown. If the arrow is incident on a 1-arrow, it becomes a 2-arrow as expected. However, this only happens when you let go of the mouse after drawing. I wonder if it could become a 2-arrow as soon as the incident 1-arrow is chosen.

**Comment by varkor** [comment]
Thanks, this is a nice idea. It's been fixed in https://github.com/varkor/quiver/commit/200866a975b27878651de4e5d41288971a610aa2.
