### ISSUE TITLE
Difficult to select arrows

### ISSUE THREAD

**Issue by DimaSamoz** [varkor/quiver#30]
The circles that allow dragging the endpoint around are quite large and can't be hidden, so sometimes it becomes difficult to select the arrow itself because the grey area around it is mostly taken up by these circles. It would be great to either
* make the circles smaller
* hide them until the user holds down some key (it's less common to want to drag the endpoint of an arrow around than just selecting it to change its label, alignment, etc.)
* select the arrow when the user clicks on the circle

![image](https://user-images.githubusercontent.com/16826557/81846811-93eb2080-954a-11ea-85b8-ba81441a407d.png)

**Comment by varkor** [comment]
Yes, I'm not happy with the user experience for manipulating arrows at the moment. I'm going to play around with different approaches.

**Comment by varkor** [comment]
This is going to be addressed by #5, where endpoints are rendered differently. I've found the experience much more pleasant so far.
![image](https://user-images.githubusercontent.com/3943692/93539189-f1074080-f947-11ea-9acb-cd68f3187379.png)
