### ISSUE TITLE
Two headed arrows

### ISSUE THREAD

**Issue by vikraman** [varkor/quiver#37]
I'd like to draw two-headed arrows in my diagrams.
Drawing two different overlapping arrows currently looks like this.
![image](https://user-images.githubusercontent.com/213959/99120647-213f2880-25f3-11eb-8598-6cdc50941a6f.png)

**Comment by varkor** [comment]
Implemented in https://github.com/varkor/quiver/commit/95b71e1ad486d6951fe89f26c7b44ca259a2c60f. This will be in the next version of **quiver**.
![image](https://user-images.githubusercontent.com/3943692/100400178-7ba5a380-304d-11eb-874d-c3966e55299a.png)
