### ISSUE TITLE
Request: Doubled edges

### ISSUE THREAD

**Issue by AviSteiner** [varkor/quiver#41]
It would be really useful to have headless arrows with double lines (i.e. long ``equals signs'').

**Comment by varkor** [comment]
Actually, this is already possible! You can choose the headless arrow style, then increase the level to 2, like this:
![image](https://user-images.githubusercontent.com/3943692/100272140-88919c80-2f52-11eb-88f7-8ff6d0c08ab0.png)
I'm going to close the issue, but let me know if you can think of a way to make this more obvious, or if this doesn't do what you want.
