### ISSUE TITLE
Allow arrow style to be set for subsequent arrows

### ISSUE THREAD

**Issue by weisJ** [varkor/quiver#42]
It would be really convenient if one could:
- Move nodes with corresponding arrows.
- Adjust curvature through dragging the middle of the arrow.
- Adjust the length of an arrow through dragging.
- Change the arrow style for all subsequently created arrows.

The first three things would need to be toggled by a modifier key e.g. shift for the first two and alt for the third.

**Comment by varkor** [comment]
> - Move nodes with corresponding arrows.

You can move vertices by dragging in the empty space around them (the cursor should change to a "move" cursor).
![image](https://user-images.githubusercontent.com/3943692/100281910-a830c100-2f62-11eb-8223-7b4e76f263d2.png)
(Let me know if this isn't what you meant.)

Adjusting the length and curvature with the cursor is an interesting idea: I will have a think about it, but I do want to be careful about cluttering the interface too much.

> - Change the arrow style for all subsequently created arrows.

It's true this isn't possible at the moment, but let me note that it is possible to select multiple arrows at once, by holding Shift (you can also use the `;` key to select using the keyboard), which makes it a little faster. I will think about the best way to implement this in the interface without introducing clutter.

**Comment by weisJ** [comment]
> > * Move nodes with corresponding arrows.
> 
> You can move vertices by dragging in the empty space around them (the cursor should change to a "move" cursor).
> [...]
> (Let me know if this isn't what you meant.)
> 

I didn't realize this is already possible. It's exactly what I meant :D.

> > * Change the arrow style for all subsequently created arrows.
> 
> It's true this isn't possible at the moment, but let me note that it is possible to select multiple arrows at once, by holding Shift (you can also use the `;` key to select using the keyboard), which makes it a little faster. I will think about the best way to implement this in the interface without introducing clutter.

Maybe there could be an option to save an arrow style together with a toolbar to select the default style. There also could be some commonly predefined styles e.g. for injections and surjections.

**Comment by varkor** [comment]
I don't think I intend to add this feature, since I think it is simple enough to draw arrows first, then change them all afterwards (and this avoids having to add a new feature to **quiver**, which I feel is complicated enough already).
