### ISSUE TITLE
Touchscreen support

### ISSUE THREAD

**Issue by weisJ** [varkor/quiver#43]
Would it be possible to add support for touch screens? Is this something you are considering?

**Comment by varkor** [comment]
Yes, I would like to support touchscreens. The main reason I have not so far is that I don't have access to a touchscreen device I can test on, but I shall try to emulate one to address this.

**Comment by varkor** [comment]
This was added in https://github.com/varkor/quiver/commit/fcb6a02765ecc3577d9622119beb6f69503feee9 and improved in several consecutive commits. It will be available in quiver 1.0.1, which is now live on https://q.uiver.app/dev. Let me know if you encounter any issues.

**Comment by weisJ** [comment]
I did a quick test and it’s working for me. Will do a more thorough test once I get to it.
