### ISSUE TITLE
A desktop client version of the app

### ISSUE THREAD

**Issue by steskalja** [varkor/quiver#44]
Are you considering a desktop client for this app? If you wanted to reuse the Javascript, you could use react native for Windows and Mac. This would be really useful since any time there is a graphic editor in a website there is too much overhead from the browser, plus it wouldn't require going to a site to use the app.

**Comment by enjoysmath** [comment]
If you didn't want to use JS for this, I offer my code:
Editing works different than in Quiver, but I would be happy to make it act like Quiver.

![python_WUcFT9dxib](https://user-images.githubusercontent.com/1606391/103979332-70589400-5132-11eb-827d-22117a69f02d.png)

It's done in PyQt5 / Python.   Using QGraphicsObjects / QGraphics Scene.  But I really think we should be doing this in 3D using Panda 3D if we're gong to rewrite anything.  My app calls `latex.exe` and `dvi2svg` and they take a few seconds to render.  Your MathJax method is instantaneous, so we would somehow have to hack together away of rendering in JS (I never got that to work using QWebView or w/e it was called).

**Comment by varkor** [comment]
@steskalja: regarding the original query, if there is a **quiver** desktop app in the future, I think the most likely route is via [Electron](https://www.electronjs.org/). This would not help with the memory overhead (though if you find **quiver** is particularly egregious for memory usage, it would be worth spending some time to optimise that), but it would be convenient in other ways, e.g. file system access.

@enjoysmath: I don't see **quiver** being rewritten in another language any time soon, which would be a major undertaking for little benefit in my opinion. That said, competition is healthy, so if you think 3D editing would be useful, I'd encourage you to experiment.

**Comment by varkor** [comment]
After more consideration, I don't think this is something I intend to build in the future. Particularly if #157 is supported, this would essentially eliminate the value of a desktop application.
