### ISSUE TITLE
Ubuntu installation

### ISSUE THREAD

**Issue by KlemenBr** [varkor/quiver#48]
The yarn package in Ubuntu comes in cmdtest package and needs to be removed and installed from the yarn Debian package repository.

## remove cmdtest
sudo apt-get remove cmdtest

## install yarn
curl -sS https://dl.yarnpkg.com/debian/pubkey.gpg | sudo apt-key add -
echo "deb https://dl.yarnpkg.com/debian/ stable main" | sudo tee /etc/apt/sources.list.d/yarn.list
sudo apt update
sudo apt install yarn

You can add this info under installation instructions.

Best regards,
Klemen Bregar

**Comment by varkor** [comment]
Thanks, I will update the README!

**Comment by varkor** [comment]
Fixed in https://github.com/varkor/quiver/commit/5d9b7b7b3606d23fd69734e296d092b645d2c593.
