### ISSUE TITLE
Curved arrows

### ISSUE THREAD

**Issue by varkor** [varkor/quiver#5]
This is the main feature that quiver is currently missing. It's actually been partially-implemented on a branch (https://github.com/varkor/quiver/tree/curves) for over a year. I just need to get around to finishing it off. The main difficulty is accounting for all of the possible arrow styles, which now need to be potentially curved too. In addition, the circular bounding "boxes" for the vertices doesn't work quite so well with curved edges.
![image](https://user-images.githubusercontent.com/3943692/74078823-dae6e880-4a26-11ea-9c8f-b488cf6619c7.png)
(An example curved arrow from the branch.)

**Comment by varkor** [comment]
For now, we'll use this issue to also track adding loops, as these features will probably be added at similar times. Both require rewriting the arrow rendering system, which is not flexible enough at present.

**Comment by Nadrieril** [comment]
I would love to have curved arrows even if the feature is not finished yet. I think that's the only feature I miss from tikcd-editor

**Comment by varkor** [comment]
I have to admit, I've had curved arrows working almost entirely for months now (I completely rewrote it since the original comment to make it more flexible). Really it just requires me to dedicate a weekend to completing it. I'll try to prioritise this.

**Comment by varkor** [comment]
I just want to note that I *am* still working on this, despite it being a month and a half since my last comment. It's very close, but it's been difficult to prioritise this sufficiently with my other commitments. However, I've recently been frustrated by the lack of curved arrows in my own work lately, which will probably motivate me to finish this off.

**Comment by varkor** [comment]
My working branch now has fully working curved arrows, with tikz-cd output, etc. Functionally, I think it's complete. However, there are a number of rendering issues remaining to iron out, and then I finally need to clean up the code. Rendering issues can be irksome to deal with, so I'm not going to make any estimates, but hopefully it'll be ready sooner rather than later.

**Comment by varkor** [comment]
I've fixed all the rendering issues that I'm aware about currently, so now I'm going to spend some time rebasing, and then I should be able to push a beta version to https://varkor.github.io/quiver/dev/.

**Comment by varkor** [comment]
You can try curved arrows out on the development version: https://varkor.github.io/quiver/dev/. I'll push it to the main site once I've ironed out any bugs that pop up.

**Comment by Exr0n** [comment]
I got confused by this, so for anyone coming by, it looks like this has been merged into the main https://q.uiver.app. To curve an arrow, click on it, then use the Curve slider on the sidebar. Cheers!
