### ISSUE TITLE
Feature request for optional modifiers to the end of arrows

### ISSUE THREAD

**Issue by zellerede** [varkor/quiver#50]
What I would like to actually see in one of my projects is an arrow _with a dot_ at the head [or tail], just like in the  a->b  arrow in the following diagram
`$$\xymatrix{a \ar[r] \ar[rd] & \!\pmb\cdot\,b\ar@{-->}[d] \\ &c}$$`

**Comment by varkor** [comment]
Out of curiosity, is this a common notation? I don't believe I've encountered it before.

I would like to add the ability to change the placement of a label along an arrow (e.g. near the tail or head). If this is a desirable feature, I could also add the option for placement at/after the end of an arrow, which should make this decoration possible.

**Comment by zellerede** [comment]
No, it's my own notation for _reflective_ / _coreflective_ arrows with respect to a subcategory. By the way, for the same reason I'd also like to encircle the objects on the right (b and c in my above diagram) into a rectangle (with bended corners). But that's another story. 
Putting a `\cdot` as optional infix subscript at (before) the beginning or after the end of the arrow could do it, though I'd like to add a normal superscript as well to name the arrow.

**Comment by varkor** [comment]
I would also like to add support for multiple labels, which would address this last issue, but it may take me a little time to get to :)

**Comment by varkor** [comment]
I'm going to close this issue, as I think it falls under the purview of #92.
