### ISSUE TITLE
Add an option to flip the corner symbol (for Cartesian squares)

### ISSUE THREAD

**Issue by nullst** [varkor/quiver#55]
First of all, thank you for making this beautiful diagram editor.

Quiver uses `\lrcorner` at the top left to denote pullback squares. I typically use a different convention: `\ulcorner` at the same position.  And similarly with the pushout squares. I'm sure I stole the notation from some seminar talk, so I'm not the only one who does that. Modifying the exported LaTeX code to follow my preferred notation is trivial with find-and-replace, but maybe an option in the editor would be nice as well. 

Perhaps clicking on the "flip" button on an arrow styled as the corner symbol should switch the corners?

**Comment by varkor** [comment]
It would be nice to add the option; I'll just need to figure out the best way to facilitate it without overcrowding. ("Flip" is intended to reflect horizontally, so isn't suitable for this task.)

**Comment by StrikeTom** [comment]
Maybe you could realize this functionality by allowing to click the "pullback/pushout"-button a second time. This is at least the first thing I tried when I wanted what OP suggested (I usually use the same notation).

**Comment by varkor** [comment]
I considered that, but was wondering how intuitive it would be. If you tried this, then maybe it is discoverable enough. I'll give it a try and see what I think.

**Comment by varkor** [comment]
This has been added in https://github.com/varkor/quiver/commit/cd3c386aefe9912aea1fdc50837094d2582a1094 and will be available in quiver 1.1.0.
[![image](https://user-images.githubusercontent.com/3943692/102697969-06835380-4232-11eb-8b66-f41f77563fe7.png)](https://q.uiver.app/dev/?q=WzAsNCxbMCwwLCJcXGJ1bGxldCJdLFsxLDAsIlxcYnVsbGV0Il0sWzAsMSwiXFxidWxsZXQiXSxbMSwxLCJcXGJ1bGxldCJdLFswLDFdLFswLDJdLFsyLDNdLFsxLDNdLFswLDMsIiIsMSx7InN0eWxlIjp7Im5hbWUiOiJjb3JuZXItaW52ZXJzZSJ9fV1d)
You can test it out on https://q.uiver.app/dev. I'm going to close this issue as solved, but let me know if you encounter any issues.
