### ISSUE TITLE
position of label along arrow

### ISSUE THREAD

**Issue by paoloperrone** [varkor/quiver#56]
Thanks for the great piece of software.

Would it be possible to edit the placement of the label on the arrow (corresponding to the option "pos" in tikzcd), and maybe also the distance between label and arrow (corresponding to "inner sep")?
Placing labels in different places may be useful for large diagrams.

Thanks!

**Comment by varkor** [comment]
Yes, this is something I intend to add, once I figure out the right interface.

This is related to https://github.com/varkor/quiver/issues/50.

**Comment by varkor** [comment]
The ability to alter the position of the label along an arrow has been added in https://github.com/varkor/quiver/commit/05981a403bba2bc40f9b7e633d02c8787db3acc1 and will be available in quiver 1.1.0.
![image](https://user-images.githubusercontent.com/3943692/103441525-8b189d80-4c46-11eb-9fba-49f63e4c4642.png)
The feature is available on [q.uiver.app/dev](https://q.uiver.app/dev) for testing.

I would have rather avoided adding more sliders, but this works for now.

I'm going to close this issue as resolved, but I'll open a new one for altering the displacement of the label from the arrow.

**Comment by varkor** [comment]
I've opened #60 for the label displacement feature request.
