### ISSUE TITLE
using quiver with texstudio - texlive

### ISSUE THREAD

**Issue by goncalosmarques** [varkor/quiver#57]
Hi quiver looks great but so far i'm unable to actually get to used in documents, I can't install the quiver package so that texstudio (with texlive distribution) would recognize it . I guess if it was on the CTAN archive it would be easier ... Do you know when you will put it there? Any other help on how to get quiver to work with texstudio? 

Thanks

Gonçalo

**Comment by varkor** [comment]
I'm not familiar with TeXstudio, but you should be able to add the `quiver.sty` file (located [here](https://q.uiver.app/quiver.sty)) to your documents, and `\usepackage{quiver}` in the preamble. At the moment, there are still several changes I anticipate making in the near future to the `quiver.sty` file, so I don't want to add it just yet as it will be outdated quickly quickly. When it's more stable, I intend to put it on CTAN.

**Comment by goncalosmarques** [comment]
It worked indeed very well . (I though the packages had to be in a special directory, did not realised they could be in the documents folder). Thanks!

**Comment by varkor** [comment]
Glad to help!

**Comment by AlexanderZeilmann** [comment]
Even if ```quiver.sty``` is still changing a lot it would be great to have it on CTAN.
There are a few reasons for this:
* About once a month I open the [TeX Live Utility](http://amaxwell.github.io/tlutility/) to update all TeX packages. It takes only around three clicks to update all packages, so having a new version of quiver frequently does not really make it more complicated for the user.
* I am working on several documents in parallel which all use quiver. So once there is a new version of ```quiver.sty``` I'd like to use, I have to go through all of the documents and update quiver.

Side note: I have never put stuff on CTAN myself, so I don't know how complicated this is.

BTW I love quiver 😍

**Comment by varkor** [comment]
I appreciate it is a little inconvenient at the moment. I will try to look into the process for adding a package to CTAN.
