### ISSUE TITLE
Adding colors to arrows (and labels)

### ISSUE THREAD

**Issue by timKraeuter** [varkor/quiver#58]
I would like to color my arrows (blue and red for my use-case).

In tikz-cd you can add the option `color=blue` for example ` \arrow["{f}", from=2-1, to=1-2, color=blue]` but this colors not only the arrow but also the label. I think the 2 should be separated.

I think the tikz-cd export is solvable quickly but changing the quiver UI and maintaining great usability could be a challenge.

I really enjoy the app! Great work 👍 .

**Comment by varkor** [comment]
I've actually been working on this feature recently :) I'm hoping that it'll be available in the next version.

**Comment by varkor** [comment]
As of https://github.com/varkor/quiver/pull/68, a colour picker has been added to **quiver**, which will be available in version 1.1.0.
![colour picker](https://user-images.githubusercontent.com/3943692/104137551-9467df80-5395-11eb-9512-fa8f0c68b3bc.png)
You can test it out on [q.uiver.app/dev](https://q.uiver.app/dev). Let me know if you have any feedback.

**Comment by timKraeuter** [comment]
Looks great! I especially like the diagram colors!

**Comment by Speculate7348** [comment]
This is very pog.
