### ISSUE TITLE
Feature request: take screenshots and copy image to clipboard

### ISSUE THREAD

**Issue by ComFreek** [varkor/quiver#59]
I often use q.uiver to quickly sketch diagrams I use in personal notes or in chats. In these media, using LaTeX is overkill. Hence, with q.uiver I often resort to hiding the grid lines by pressing the button in the UI and manually taking a screenshot.

**Comment by varkor** [comment]
I would love to add this, but at the moment it's blocked on https://github.com/KaTeX/KaTeX/issues/375: it'd only be possible to save screenshots without the labels (or use a different LaTeX renderer like MathJax, which will not look exactly the same, and take some work to integrate). This is essentially the same feature as https://github.com/varkor/quiver/issues/8, so I'm going to close this issue in favour of that one.
