### ISSUE TITLE
Doesn't make with GnuWin make for windows

### ISSUE THREAD

**Issue by enjoysmath** [varkor/quiver#61]
http://gnuwin32.sourceforge.net/packages/make.htm

```
C:\Users\FruitfulApproach\Desktop\Quiver\quiver>make
set -e
Environment variable -e not defined
make: *** [all] Error 1

C:\Users\FruitfulApproach\Desktop\Quiver\quiver>
```

**Comment by varkor** [comment]
[`set -e`](http://www.gnu.org/savannah-checkouts/gnu/bash/manual/bash.html#The-Set-Builtin) is used to ensure errors cause bash to exit. This isn't so important for the default make target, so as a temporary solution you could delete the line `set -e` and run make again.

**Comment by enjoysmath** [comment]
```
C:\Users\FruitfulApproach\Desktop\Quiver\quiver>make
git submodule update --init --recursive
cd src/KaTeX
yarn
yarn install v1.22.5
info No lockfile found.
[1/4] Resolving packages...
[2/4] Fetching packages...
[3/4] Linking dependencies...
[4/4] Building fresh packages...

success Saved lockfile.
Done in 0.69s.
yarn build
yarn run v1.22.5
error Couldn't find a package.json file in "C:\\Users\\FruitfulApproach\\Desktop\\Quiver\\quiver"
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
make: *** [all] Error 1

C:\Users\FruitfulApproach\Desktop\Quiver\quiver>
```

**Comment by varkor** [comment]
I suspect GnuWin doesn't support `.ONESHELL`. You should be able to run the following commands in bash manually to set quiver up.
```bash
git submodule update --init --recursive
cd src/KaTeX
yarn
yarn build
```

**Comment by enjoysmath** [comment]
```
$ yarn
yarn install v1.22.5
[1/4] Resolving packages...
[2/4] Fetching packages...
error An unexpected error occurred: "C:\\Users\\FruitfulApproach\\AppData\\Local\\Yarn\\Cache\\v6\\npm-cliui-4.1.0-348422dbe82d800b3022eef4f6ac10bf2e4d1b49-i
ntegrity\\node_modules\\cliui\\.yarn-metadata.json: Unexpected end of JSON input".
info If you think this is a bug, please open a bug report with the information provided in "C:\\Users\\FruitfulApproach\\Desktop\\Quiver\\quiver\\src\\KaTeX\
\yarn-error.log".
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
```

**Comment by varkor** [comment]
Unfortunately I've not encountered this error before. Perhaps one of the solutions [in this thread](https://github.com/yarnpkg/yarn/issues/660#issuecomment-535803459) could be helpful. Alternatively, since the step involving yarn is only necessary to install KaTeX, it's possible a [different method](https://katex.org/docs/node.html) of installing would work, e.g. `npm install katex`. (I don't think these alternatives were available when I originally added KaTeX support, so I haven't tried them, but it could be worth experimenting to see whether these cause less issues than yarn.)

**Comment by varkor** [comment]
If you don't manage to get this working, I'll investigate a different method for adding KaTeX that doesn't involve yarn, because yarn has proven problematic in the past too.

**Comment by enjoysmath** [comment]
Running `npm install katex` creates a node_modules dir.  I ran it in the parent dir to src.  How do I get it to store packages in your folder structure?

**Comment by varkor** [comment]
I think the most straightforward solution is to move from having KaTeX as a submodule, to simply downloading a prebuilt release and using that directly. As-is, this won't work straight away, because some of the paths to KaTeX resources will be incorrect in the quiver source. I would imagine it would be mostly straightforward to make the change (searching for "KaTeX" in the quiver source), so if you want to run it locally now, that's something to try. Otherwise, I will do this myself tomorrow and post an update on this issue when it's fixed.

**Comment by enjoysmath** [comment]
@varkor yes, please have github inform me when it's ready!  I left a long write-up in the GitHub discussions tab for Quiver.  Let me know if that's something you'd be interested in integrating into your app.  Doing that would make my job half as hard.  I know personally from coding a CD editor in PyQt5 how hard it is to get it work right.  Cheers.

**Comment by varkor** [comment]
I've switched over to using a prebuilt release of KaTeX in https://github.com/varkor/quiver/tree/prebuilt-katex. For technical reasons, I won't be able to switch to using this on `master` until version 1.1.0 is released (hopefully not long now). However, you can clone the `prebuilt-katex` branch and follow the new instructions in the read-me, which should address your problem (you'll need to follow the manual instructions, as the Makefile still won't work for you).

**Comment by enjoysmath** [comment]
@varkor 

I switched to that branch in the dropdown, cloned the repo, and downloaded the katex.zip.  I placed and renamed to to KaTeX the folder under src/KaTeX and still getting KaTeX load error in quiver.

**Comment by enjoysmath** [comment]
@varkor 

Okay, I got it to work.  I created a new folder under KaTeX called dist/ and pasted the contents of KaTeX into it.  Accordingly with the source code that loads the library.

**Comment by varkor** [comment]
Glad you managed to get it working! Soon I'll switch everything over and it should be much simpler to get started. Thanks for your feedback!

**Comment by enjoysmath** [comment]
Thanks for creating such great software for mathematicians.  We are
indebted to you as a community :)

So you recommend an API for connecting to other apps, but what if I just
forked the repo and embedded the database query code into quiver?

I guess I could do that for now, and then when you have an API available,
switch over to using it and your original repo.

**Comment by enjoysmath** [comment]
Also, what part of the code should I be looking at for injecting my
database query code, such as the parts that create an arrow / node, etc?

As you can imagine, looking at the code for the first time can be
overwhelming to a person that didn't author it.

**Comment by enjoysmath** [comment]
Okay, I forked the code, and noticed that you removed the dist/ in the code string on the prebuilt-katex branch   We are coding, mon.  This is fun :)

**Comment by varkor** [comment]
> So you recommend an API for connecting to other apps, but what if I just
forked the repo and embedded the database query code into quiver?

That sounds like a good starting point.

> Also, what part of the code should I be looking at for injecting my database query code, such as the parts that create an arrow / node, etc?

Perhaps to start off with, don't worry about the interaction: just try to get **quiver** loading a diagram, specified by your database. The place to start is https://github.com/varkor/quiver/blob/master/src/quiver.js, which specifies the data structure that is used for the diagrams, as well as `QuiverImportExport.base64`, which controls exporting and importing diagrams from and to base64. You might be able to make a new `QuiverImportExport.database`, based on this code, that instead queries your database to figure out how to build a new diagram.
