### ISSUE TITLE
Quiver needs support for "Remarks"

### ISSUE THREAD

**Issue by enjoysmath** [varkor/quiver#64]
Trying to mimic a remark using a node currently looks like:
https://q.uiver.app/?q=WzAsMyxbMCwxLCJcXG1hdGhzY3J7Rn0iXSxbMSwxLCJcXG1hdGhzY3J7R30iXSxbMCwwLCJcXHRleHR7TGV0IH0gXFx2YXJwaGkgXFx0ZXh0eyBiZSBhIG1vcnBoaXNtIG9mIEFiIHNoZWF2ZXN9Il0sWzAsMSwiXFx2YXJwaGkiXV0=

**Comment by varkor** [comment]
I'm wondering what context you want to put remarks in your diagram like this? I would expect that these would usually be added in a LaTeX document (as ordinary text) after exporting the diagram from **quiver**. Are you using it as a standalone tool to design worksheets or something like that?

**Comment by enjoysmath** [comment]
@varkor I have decided to use your app as is by embedding it in an iframe.  This seems to work:

![image](https://user-images.githubusercontent.com/1606391/103978851-4ce11980-5131-11eb-9673-0046475706ca.png)

That iframes your `https://https://q.uiver.app/` in a Flask / Jinja2 html template.  So, closing this.  Remarks will be a feature that is displayed in another div on that page.  They will still be stored in a graph database connected via a graph db edge ":HasRemark" to a :Diagram node.
