### ISSUE TITLE
New to JS, what JS IDE do you recommend?

### ISSUE THREAD

**Issue by enjoysmath** [varkor/quiver#65]
I've downloaded Visual Studio Code, and simply opened the folder.

I would like an IDE that let's you debug javascript the same way I do python code in Wingware.  Is that possible?

What JS IDE do you recommend?

**Comment by enjoysmath** [comment]
Okay, I've answered my own question partially.  You open the quiver folder, then go to the index.html in the VSCode file navigator, then go to "Run > Debug > (Select Edge: Launch)" for the microsoft Edge browser, I set a breakpoint in JS and it triggered!

Still interested to know what IDE you use.

**Comment by varkor** [comment]
I use Visual Studio Code, and usually debug in Chrome using the DevTools (though Firefox, and most of the other web browsers, have good debuggers too). So it sounds like you're on the right track :)
