### ISSUE TITLE
API to talk to quiver even if it just gives the base64 encoding which we can then decode.

### ISSUE THREAD

**Issue by enjoysmath** [varkor/quiver#66]
But preferably a complete JSON dictionary describing the graph would be nice.

I'm not sure how to do this, but this is the most modular thing we can do (for our app that wants to add Neo4j database support to Quiver).

**Comment by varkor** [comment]
If you're forking **quiver** to integrate it into another system, you should just be able to `QuiverImportExport.base64` `export` method:
https://github.com/varkor/quiver/blob/c567eb61a3dca41e8b95d50009f67f0d2da37192/src/quiver.js#L689
which will give you a base64 string you can decode. The data format is described above, and the `decode` method should guide you.

**Comment by varkor** [comment]
I'm going to close this issue, because I think https://github.com/varkor/quiver/issues/66#issuecomment-757068076 addresses your use case. If you have other use cases for which that solution is insufficient, we can reopen the discussion.
