### ISSUE TITLE
I want the ability to move objects with mouse instead of B then arrow keys.

### ISSUE THREAD

**Issue by enjoysmath** [varkor/quiver#70]
Abilty to move objects with mouse instead of B then arrow keys.

The B mechanism sometimes is picky and it's more intuitive to just let the users drag around objects.  Maybe B mode can toggle the mode in which mouse drags do this.  No need for fanciness such as select many assuming that's more difficult.  

The user friendliness rating would go through the roof if you had this feature.

_By the way, I have Neo4j hosted on (another server) and Django hosted on heroku finally!  I'm pretty excited about database support for quiver._

**Comment by varkor** [comment]
You can already move objects around by [clicking and dragging](https://github.com/varkor/quiver/issues/9#issuecomment-591557946) in the empty space around them. It works with multiple selection. I'd be happy to hear how to make this more discoverable; it's in the tips when you first open **quiver**, but I think people just skip them.
