### ISSUE TITLE
Vertex sizes are messed up on page load

### ISSUE THREAD

**Issue by Qqwy** [varkor/quiver#72]
When loading the following diagram: https://q.uiver.app/?q=WzAsOSxbMSwyLCJcXHNjcmlwdHNpemUgb3JjaGVzdHJhdGUiXSxbMSwzLCJcXHNjcmlwdHNpemUgc3RhdGUiXSxbMSw0LCJcXHNjcmlwdHNpemUgcnVubmVyfm1vZHVsZXMiXSxbMSw1LCJcXHNjcmlwdHNpemUgam9icyJdLFsxLDYsImV2ZW50fnF1ZXVlcyJdLFszLDEsInJlYWN0b3JzXFxcXCBcXHRleHRzZntcXHNjcmlwdHNpemUgcnVuIG5ldyBjb21tYW5kcyB3aGVuIHBhcnRpY3VsYXIgZXZlbnRzIGhhcHBlbn0iXSxbMCw2LCJiZWFjb25zXFxcXCBcXHRleHRzZntcXHNjcmlwdHNpemUgYWRkIGV2ZW50cyBmcm9tIGV4dGVybmFsIHByb2Nlc3NlcyAob24gdGhlIG1pbmlvbil9Il0sWzAsMSwiY29tbWFuZH5pbnRlcmZhY2UiXSxbMCwwLCJcXGJ1bGxldCJdLFs2LDRdLFs0LDUsIiIsMCx7ImN1cnZlIjo1LCJzdHlsZSI6eyJib2R5Ijp7Im5hbWUiOiJkYXNoZWQifX19XSxbNywwLCIiLDAseyJjdXJ2ZSI6M31dLFs3LDEsIiIsMix7ImN1cnZlIjozfV0sWzcsMiwiIiwyLHsiY3VydmUiOjR9XSxbNywzLCIiLDIseyJjdXJ2ZSI6NX1dLFswLDFdLFsxLDJdLFsyLDNdLFszLDRdLFs1LDddLFs4LDddXQ==

it first looks like this

![image](https://user-images.githubusercontent.com/5345745/105187676-56a44d00-5b33-11eb-910e-fd78c55ec2a8.png)

Only after making a change to a vector description (such as adding and removing a space somewhere), the diagram is rectified to 

![image](https://user-images.githubusercontent.com/5345745/105187781-76d40c00-5b33-11eb-8be7-d9b39ebae735.png)

The contents of the vector descriptions are of course rather long (we're using Quiver for diagrams outside of category theory), but it still is odd behaviour that probably warrants investigation.

Thanks for the great app!

**Comment by varkor** [comment]
Thanks for reporting. I have been aware of this issue, but it's quite difficult to test as it's nondeterministic. (For instance, if I open your link, it loads at the correct size for me.) I'll try to investigate it further.

**Comment by Qqwy** [comment]
Very curious. If it helps to further pin this down, I am using Firefox 84.0.2 on an x64 Manjaro Linux machine.

**Comment by varkor** [comment]
Okay, I've managed to reproduce this reliably. The issue is that KaTeX loads fonts lazily and so when the page initially loads, before the fonts are ready, rendering KaTeX will produce the wrong width/height measurements at first, because it can only calculate them correctly once the fonts have loaded. However, **quiver** doesn't know when the fonts have been loaded, so it attempts to get the dimensions immediately. I'm trying to work out how to address this.

**Comment by varkor** [comment]
I believe https://github.com/varkor/quiver/commit/d42fb6ce1b286b7e4fc7292a36350ba7ffaee7d7 should have addressed the issue. Can you try opening the diagram on [q.uiver.app/dev](https://q.uiver.app/dev/?q=WzAsOSxbMSwyLCJcXHNjcmlwdHNpemUgb3JjaGVzdHJhdGUiXSxbMSwzLCJcXHNjcmlwdHNpemUgc3RhdGUiXSxbMSw0LCJcXHNjcmlwdHNpemUgcnVubmVyfm1vZHVsZXMiXSxbMSw1LCJcXHNjcmlwdHNpemUgam9icyJdLFsxLDYsImV2ZW50fnF1ZXVlcyJdLFszLDEsInJlYWN0b3JzXFxcXCBcXHRleHRzZntcXHNjcmlwdHNpemUgcnVuIG5ldyBjb21tYW5kcyB3aGVuIHBhcnRpY3VsYXIgZXZlbnRzIGhhcHBlbn0iXSxbMCw2LCJiZWFjb25zXFxcXCBcXHRleHRzZntcXHNjcmlwdHNpemUgYWRkIGV2ZW50cyBmcm9tIGV4dGVybmFsIHByb2Nlc3NlcyAob24gdGhlIG1pbmlvbil9Il0sWzAsMSwiY29tbWFuZH5pbnRlcmZhY2UiXSxbMCwwLCJcXGJ1bGxldCJdLFs2LDRdLFs0LDUsIiIsMCx7ImN1cnZlIjo1LCJzdHlsZSI6eyJib2R5Ijp7Im5hbWUiOiJkYXNoZWQifX19XSxbNywwLCIiLDAseyJjdXJ2ZSI6M31dLFs3LDEsIiIsMix7ImN1cnZlIjozfV0sWzcsMiwiIiwyLHsiY3VydmUiOjR9XSxbNywzLCIiLDIseyJjdXJ2ZSI6NX1dLFswLDFdLFsxLDJdLFsyLDNdLFszLDRdLFs1LDddLFs4LDddXQ==) to see whether it loads correctly?

**Comment by Qqwy** [comment]
> Can you try opening the diagram on q.uiver.app/dev to see whether it loads correctly?

Yes, it seems to work correctly :+1:

**Comment by varkor** [comment]
Great. I'd like to do a little more testing before pushing this live, but it should be available soon. If it's frustrating before then, you can use [q.uiver.app/dev](https://q.uiver.app/dev) in the meantime.
