### ISSUE TITLE
What does "Show Queue" do and can I simply remove it from the app (or is it completely necessary)?

### ISSUE THREAD

**Issue by enjoysmath** [varkor/quiver#73]
Not quite getting what "Show Queue" does / means.  

I'm trying to lessen the number of buttons in the GUI in order to fit smaller screens:

![image](https://user-images.githubusercontent.com/1606391/105431799-38118500-5c0b-11eb-9d2b-6cd2299819a6.png)

I'm working on a CD database app with Quiver as the CD editor.

**Comment by enjoysmath** [comment]
I've removed it a long with a few other buttons such as "Deselect All".

**Comment by NickHu** [comment]
I also came here to try to understand what it is for; when you create new cells, they are 'queued' so you can cycle through them with Tab (like UI elements in a page). The button shows/hides labels to indicate things you can tab to.

**Comment by enjoysmath** [comment]
Very neat
