### ISSUE TITLE
How could I stop click events from propogating to the background quiver canvas?

### ISSUE THREAD

**Issue by enjoysmath** [varkor/quiver#74]
@varkor 

Here is a video of the bug in my QuiverDatabase app:

https://youtu.be/nDU5M07GBSs

I got the X-editable (CSS lib) buttons to the front using CSS: z-index: 1.  Now the mouse click is also going on to quiver.  Anyway to prevent this?

**Comment by varkor** [comment]
You can call `event.stopPropagation();` inside the `click` event. This is not specific to **quiver**, so it might be beneficial to look into tutorials for JavaScript and the DOM to get you started with these kind of questions.

**Comment by enjoysmath** [comment]
Fixed it by adding some code into quiver:

![image](https://user-images.githubusercontent.com/1606391/105439217-4bc3e800-5c19-11eb-8888-c31aa106fd32.png)

```
        // QuiverDatabase: stop event propogation on to quiver when click is in the site's button pane
        const database_control_pane = new DOM.Div({
            id: "database-control-pane",
            class: "lower-left-pane pane container-fluid",
        }).add(new DOM.Div({class: "row"})
            .add(new DOM.Div({class:"col-md-12"})
            .add(new DOM.Element("h4")
            .add(new DOM.Element("strong"))
            .add(new DOM.Element("a", {
                "id":"diagram-name-edit",
                "data-type": "text",
                "href": "#",
                "data-title":"Diagram Name",
                "style": "border:none",
                /* TODO: add pk key to html script:
                data-pk="{{ diagram_id }}" href="#" */
            })/*todo initialize with current diagram name in html script */))));
        panes.push(database_control_pane);
```

event.stopPropagtaion() would not work from html.  So I figured, I had to add in the buttons to a pane greated in Quiver.

**Comment by enjoysmath** [comment]
@varkor Thanks.  You have been really helpful in getting me started with quiver.  I am forever grateful :)
