### ISSUE TITLE
Add duplicate selection action

### ISSUE THREAD

**Issue by jfgarciava** [varkor/quiver#80]
Thanks for the great editor.
It would be useful if one could duplicate some part of the diagram.
The workflow would be:
1. Select some cells.
2. Press the duplicate command, for instance ctrl+D.
3. Move the focus to some free position on the grid.
4. Press the paste command, for instance RET, to obtain a duplicate of the selection, at the selected position.

  I think it would be similar to the move action.

**Comment by varkor** [comment]
This is the kind of functionality I had imagined for #21, so I'm going to close this issue in favour of that one.
