### ISSUE TITLE
Bug: Select-All followed by Move seems to have no exit

### ISSUE THREAD

**Issue by eric-downes** [varkor/quiver#83]
Behavior: 

Cannot seem to exit Move state after Select All.

To reproduce:

1. Create a diagram
2. Select All
3. Position the mouse to get a "Move" Cursor 
4. Move the diagram
5. Try to stop moving the diagram

Enter, Esc, Ctrl-C, Ctrl-D, etc do not exit the move state.  If there is a means to do so, perhaps display this to the user.

Thanks so much for this great software!

**Comment by varkor** [comment]
This sounds like a bug, but I'm having trouble reproducing it. To clarify, you click down the mouse to start dragging, drag the diagram somewhere, then release the mouse, and it doesn't stop moving the diagram when you move the mouse?

Does it happen even with a very small diagram, e.g. involving just one or two objects?

**Comment by eric-downes** [comment]
Perhaps this is only a bug with my mouse then; I'm using a 3M ergonomic mouse.  But yes, when I release, the diagram doesn't snap to the frame.

After reading your description of what is supposed to happen, I discovered that if I double click enough it seems to work.

Eric

**Comment by eric-downes** [comment]
I'll go ahead and close this, since it seems to be an obscure hardware issue.

**Comment by varkor** [comment]
I'd like to fix this if possible, but it could be difficult if I can't find a way to reproduce. Sorry!

**Comment by eric-downes** [comment]
Here's what I recommend -- if you can just make ESC a general purpose "exit out of whatever special mode I'm in" key, that would give the needed functionality, and might be useful to other people as well.

If you want I can make this a Feature Request issue.

**Comment by varkor** [comment]
Yes, that would be a good fix. Escape already behaves like this for most other modes, so it makes sense to make it have this behaviour for moving cells too. I'll reopen this issue to use as a tracking issue for this behaviour.

**Comment by varkor** [comment]
> Escape already behaves like this for most other modes, so it makes sense to make it have this behaviour for moving cells too.

This is fixed by https://github.com/varkor/quiver/commit/3e8e519c20fe9bf9a5ce0557a79aa7ad0487bab5 and will be available in https://q.uiver.app/ soon.
