### ISSUE TITLE
Open quiver.sty in new tab also starts a download

### ISSUE THREAD

**Issue by AlexanderZeilmann** [varkor/quiver#84]
When I'm in the LaTeX export screen clicking on  ```download quiver.sty``` and ```open it in a new tab``` both initiate a download.

I (very rough) guess that this is because the file is served with the ```content-type``` ```application/octet-stream``` and then the browser does not know what to do with the file and tries to download it. 
```https://raw.githubusercontent.com/varkor/quiver/master/src/quiver.sty``` is served with the ```content-type``` ```plain```, so the browser says "Oh this is just a plain text file so let me display it."

Probably the quickest fix is to link directly to the file ```https://raw.githubusercontent.com/varkor/quiver/master/src/quiver.sty```.

I am on a Mac and could reproduce the behaviour in the following browsers:
* Firefox 86
* Brave 1.21.77
* Safari 13.1

**Comment by varkor** [comment]
Thanks for pointing this out: I must have only checked this behaviour in Chrome, which does seem to display the file as plain text. I've followed your suggestion in https://github.com/varkor/quiver/commit/7c87ee522e3b51d270f70ed244eb4b837bed750e. It's a pity that it's not possible to override the MIME type in GitHub Pages directly.
