### ISSUE TITLE
Edge creation not possible on touchscreens

### ISSUE THREAD

**Issue by AlexanderZeilmann** [varkor/quiver#86]
On touchscreens, it is currently not possible to create edges between nodes. (Or at least I do not know how to do it.)

Currently, when I click a node and track my finger to a different node, an edge appears. However, this edge is not permanent. When I click something else, the edge disappears again.

I can reproduce the behavior on my tablet and smartphone.
The video below hopefully illustrates it.

https://user-images.githubusercontent.com/901391/113163769-c2481c00-9240-11eb-8db3-98eacbee5068.MP4

**Comment by varkor** [comment]
This is a regression, but I'm not sure when the bug might have been introduced. Unfortunately, I do not frequently test on touchscreens as I don't have a suitable device. I will try to look into this soon.

**Comment by varkor** [comment]
This was fixed in https://github.com/varkor/quiver/commit/c48f97d743b7d99ef288b89b069103a44a0428e8 and is now available on [q.uiver.app](https://q.uiver.app/). Thanks for reporting!

**Comment by AlexanderZeilmann** [comment]
Wow, that was quick. 

I can confirm that it is working. Thank you! 🥳
