### ISSUE TITLE
Curve arrow isn't rendering

### ISSUE THREAD

**Issue by big-lion** [varkor/quiver#89]
Currently the code outputs curved arrows like this:

`\arrow[curve={height=-30pt}, from=1-1, to=1-3]
`

This isn't compiling at my editor, and I've been manually replacing it with

`	\arrow[bend right = 30 pt, from=1-1, to=1-3]
`

I don't know if the issue is at my side.

**Comment by varkor** [comment]
Have you included the [quiver.sty](https://q.uiver.app/quiver.sty) package?

**Comment by varkor** [comment]
Closing due to lack of information. I imagine the package simply needed to be included.
