### ISSUE TITLE
Import Latex

### ISSUE THREAD

**Issue by Hamad-Aly** [varkor/quiver#93]
been using the app for a week now and I have to say it s great but It would be great if one may import LaTeX codes, right now I m able only to copy LaTeX but unable to paste my own codes and do changes on commutative diagrams.

**Comment by varkor** [comment]
Thanks for the request! There's an open issue for this here: https://github.com/varkor/quiver/issues/40. It's a feature I'd like to add at some point, though I don't currently have the time. I'm going to close this issue in favour of that one.
